namespace Common.Enums
{
    //public enum MessageIdType
    //{
    //    [IntValueAttribute(49)]
    //    LoginSuccess = 1,
    //    [IntValueAttribute(49)]
    //    LoginUnSuccess = 2,
    //    [IntValueAttribute(49)]
    //    Exception = 3,
    //    [IntValueAttribute(49)]
    //    CustomerAccountExists = 4,
    //    [IntValueAttribute(49)]
    //    CustomerAccountDoesNotExists = 5,
    //    [IntValueAttribute(49)]
    //    BeneficiaryDetailsFound = 6,
    //    [IntValueAttribute(49)]
    //    BeneficiaryDetailsNotFound = 7,
    //    [IntValueAttribute(49)]
    //    BeneficiaryAdded = 8,
    //    [IntValueAttribute(49)]
    //    BeneficiaryCouldNotBeAdded = 9,
    //    [IntValueAttribute(49)]
    //    IFSCDetailsFound = 10,
    //    [IntValueAttribute(49)]
    //    IFSCDetailsNotFound = 11,
    //    [IntValueAttribute(49)]
    //    BiometricVerificationSuccess = 12,
    //    [IntValueAttribute(49)]
    //    BiometricVerificationFailed = 13,
    //    [IntValueAttribute(49)]
    //    AccountToAccountFundTransferSuccess = 14,
    //    [IntValueAttribute(49)]
    //    AccountToAccountFundTransferFailed = 15,
    //    [IntValueAttribute(49)]
    //    IMPSFundTransferSuccess = 16,
    //    [IntValueAttribute(49)]
    //    IMPSFundTransferFailed = 17,
    //    [IntValueAttribute(49)]
    //    NEFTFundTransferSuccess = 18,
    //    [IntValueAttribute(49)]
    //    NEFTFundTransferFailed = 19,
    //    [IntValueAttribute(49)]
    //    RTGSFundTransferSuccess = 20,
    //    [IntValueAttribute(49)]
    //    RTGSFundTransferFailed = 21,
    //    [IntValueAttribute(49)]
    //    KYCExists = 22,
    //    [IntValueAttribute(49)]
    //    KYCDoesNotExists = 23,
    //    [IntValueAttribute(49)]
    //    CustomerDocumentsUploadedSuccessfully = 24,
    //    [IntValueAttribute(49)]
    //    CustomerDocumentsCouldNotbeUploadedSuccessfully = 25,
    //    [IntValueAttribute(49)]
    //    FingerPrintDetailsisSaved = 26,
    //    [IntValueAttribute(49)]
    //    FingerPrintDetailsisnotSaved = 27,
    //    [IntValueAttribute(49)]
    //    CustomerAccountNumberIsCreated = 28,
    //    [IntValueAttribute(49)]
    //    AccountOpeningCardLinkedSuccess = 361,
    //    [IntValueAttribute(49)]
    //    CustomerAccountNumberIsNotCreated = 29,
    //    [IntValueAttribute(49)]
    //    CashDepositSuccess = 30,
    //    [IntValueAttribute(49)]
    //    CashDepositFailed = 31,
    //    [IntValueAttribute(49)]
    //    CASAPLUSFundTransferSuccess = 731,
    //    [IntValueAttribute(49)]
    //    CASAPLUSFundTransferFailed = 732,
    //    [IntValueAttribute(49)]
    //    CASAPLUSViewBalanceSuccess = 733,
    //    [IntValueAttribute(49)]
    //    CASAPLUSViewBalanceFailed = 734,
    //    [IntValueAttribute(49)]
    //    CASAPLUSViewStatementSuccess = 808,
    //    [IntValueAttribute(49)]
    //    CASAPLUSViewStatementFailed = 809,
    //    [IntValueAttribute(49)]
    //    CashWithdrawSuccess = 32,
    //    [IntValueAttribute(49)]
    //    CashWithdrawFailed = 33,
    //    [IntValueAttribute(49)]
    //    OTPGeneratedSuccessfully = 50,
    //    [IntValueAttribute(49)]
    //    OTPGenerationFailed = 51,
    //    [IntValueAttribute(49)]
    //    OTPAlreadyUsed = 52,
    //    [IntValueAttribute(49)]
    //    OTPVerifiedSuccessfully = 53,
    //    [IntValueAttribute(49)]
    //    OTPVerificationFailed = 54,
    //    [IntValueAttribute(49)]
    //    OTPHasBeenExpired = 55,
    //    [IntValueAttribute(49)]
    //    SMSSentSuccessfully = 56,
    //    [IntValueAttribute(49)]
    //    SMSSendingFailed = 57,
    //    [IntValueAttribute(49)]
    //    InsertOTPSuccess = 58,
    //    [IntValueAttribute(49)]
    //    InsertOTPFailed = 59,
    //    [IntValueAttribute(49)]
    //    InsertSMSSuccess = 60,
    //    [IntValueAttribute(49)]
    //    InsertSMSFailed = 61,
    //    [IntValueAttribute(49)]
    //    ServerError = 64,
    //    [IntValueAttribute(49)]
    //    AuthenticateSuccess = 65,
    //    [IntValueAttribute(49)]
    //    AuthenticateUnSuccess = 66,
    //    SessionExpired = 67,
    //    NotificationSentSuccessfully = 68,
    //    NotificationSentFailed = 69,
    //    CustomerDetailsFound = 70,
    //    CustomerDetailsNotFound = 71,
    //    BeneficiaryDeleted = 72,
    //    BeneficiaryCouldNotDeleted = 73,
    //    EmailloadingSuccessful = 74,
    //    EmailloadingFailed = 75,
    //    CashCountSuccess = 76,
    //    CashCountError = 77,
    //    MiniStatementSuccessful = 78,
    //    MiniStatementFailed = 79,
    //    InterestCertificateFailed = 1011,
    //    InterestCertificateSuccessful = 1012,
    //    IFSCCodeSuccess = 80,
    //    IFSCCodeError = 81,
    //    InstaKitNumberSuccess = 82,
    //    InstaKitNumberFailed = 83,
    //    NSDLSuccess = 84,
    //    NSDLFailed = 85,
    //    FingerPrintMatchSucess = 86,
    //    FingerPrintMatchFailed = 87,
    //    AUADataFetchSucess = 88,
    //    AUADataFetchFailed = 89,
    //    UIDFoundSucess = 90,
    //    UIDFoundFailed = 91,
    //    LogoutSuccessful = 92,
    //    LogoutFailed = 93,
    //    NEFTTransactionTimingSuccess = 94,
    //    NEFTTransactionTimingFailed = 95,
    //    AuthContextDetailsSuccess = 96,
    //    AuthContextDetailsFailed = 97,
    //    UnableToGetEncryptionKey = 98,
    //    TellerProofSuccess = 99,
    //    TellerProofFailed = 100,
    //    BranchProofSuccess = 102,
    //    BranchProofFailed = 103,
    //    AccountHistorySuccess = 104,
    //    AccountHistoryFailed = 105,
    //    CustomerUpdateSuccessfully = 106,
    //    CustomerUpdateFailed = 107,
    //    ChargesCheckSuccessfully = 108,
    //    ChargesCheckFailed = 109,
    //    PostTransactionSuccessfully = 110,
    //    PostTransactionFailed = 111,
    //    DeleteBeneficiarySuccessful = 112,
    //    DeleteBeneficiaryFailed = 113,
    //    PanValidationSuccess = 114,
    //    PanValidationFailed = 115,
    //    SetSMSCommunicationPreferenceSuccess = 901,
    //    SetSMSCommunicationPreferenceFailed = 902,
    //    GetCustomerPhotoSuccess = 116,
    //    GetCustomerPhotoFailed = 117,
    //    FpVerificationSuccess = 118,
    //    FpVerificationFailed = 119,
    //    UpdateCustomerPhotoSuccess = 120,
    //    UpdateCustomerPhotoFailed = 121,
    //    TokenValidationSuccess = 122,
    //    TokenValidationFailed = 123,
    //    AddBillerSuccesful = 124,
    //    AddBillerFailed = 125,
    //    RechargeQuerySuccessful = 126,
    //    RechargeQueryFailed = 127,
    //    ValidateRechargeSuccessful = 128,
    //    ValidateRechargeFailed = 129,
    //    PaymentandRechargeDetailsSourceDebitSuccessful = 130,
    //    PaymentandRechargeDetailsSourceDebitFailed = 131,
    //    DeleteBillersSuccessful = 132,
    //    DeleteBillersFailed = 133,
    //    ViewBillsSuccessful = 134,
    //    ViewBillsFailed = 135,
    //    PaymentOnlyDetailsSuccesful = 136,
    //    PaymentOnlyDetailsFailed = 137,
    //    ViewBillerAccountSuccessful = 138,
    //    ViewBillerAccountFailed = 139,
    //    ViewLastPaidBillsSuccessful = 140,
    //    ViewLastPaidBillsFailed = 141,
    //    CheckTransactionStatusSuccessful = 142,
    //    CheckTransactionStatusFailed = 143,
    //    BillerValidationsSuccessful = 144,
    //    BillerValidationsFailed = 145,
    //    SetAutoPaySuccesful = 146,
    //    SetAutoPayFailed = 147,
    //    ViewScheduledBillsSuccesful = 148,
    //    ViewScheduledBillsFailed = 149,
    //    Modify_DeleteAutoPaySuccessful = 150,
    //    Modify_DeleteAutoPayFailed = 151,
    //    StopScheduledTransactionSuccessful = 152,
    //    StopScheduledTransactionFailed = 153,
    //    BillFetchDetailsSuccesful = 154,
    //    BillFetchDetailsFailed = 155,
    //    FPTemplatenotfound = 156,
    //    IMPSWalletAccountSuccess = 158,
    //    IMPSWalletAccountFailed = 159,
    //    PassbookUpdationSuccessful = 160,
    //    PassbookUpdationFailed = 161,
    //    AadhaarLPGSeedingSuccessful = 162,
    //    AadhaarLPGSeedingFailed = 163,
    //    NomineeAdditionSuccessful = 164,
    //    NomineeAdditionFailed = 165,
    //    NominationupadationSuccessful = 166,
    //    NominationupadationFailed = 167,
    //    DBTLSeedingSuccessful = 168,
    //    DBTLSeedingFailed = 169,
    //    RevisionDetailsSuccess = 170,
    //    RevisionDetailsFailed = 171,
    //    GetDMSdataSuccess = 172,
    //    GetDMSdataFailed = 173,
    //    //Added by Vaibhav
    //    #region [Krazy Bee Loan]
    //    KrazybeeDataInsertionSuccess = 700605,
    //    KrazybeeDataInsertionFailed = 700606,
    //    IIFlCustomerNotExists = 700607,
    //    IIFlCustomerExists = 700608,
    //    #endregion

    //    #region [Digital Loan]
    //    Loantokencreationfailed = 700615,
    //    DocumentMasterfound = 700616,
    //    DocumentMasterNotfound = 700617,
    //    LoanRequestSubmittedSuccessfully = 700618,
    //    LoanRequestFailed = 700619,
    //    Lenderfielddetailsfound = 700620,
    //    Lenderfielddetailsnotfound = 700621,
    //    Loanstatusavailable = 700622,
    //    Loanstatusnotavailable = 700623,
    //    Lenderdetailsfound = 700624,
    //    Lenderdetailsnotfound = 700625,

    //    Eligible = 700630,
    //    NotEligible = 700631,
    //    LoanDetailsFound = 700632,
    //    LoanDetailsNotFound = 700633,
    //    WithdrawalSuccessfull = 700634,
    //    WithdrawalFailed = 700635,
    //    AccountStatementGenerate = 700636,
    //    AccountStatementFailed = 700637,
    //    RepaymentDone = 700638,
    //    RepaymentFails = 700639,
    //    #endregion

    //    #region [Cleaver Tap Myprofile]
    //    PreferredlanguageSelected = 700609,
    //    PreferredlanguageNotAvailable = 700610,
    //    PreferredlanguageSaved = 700611,
    //    PreferredlanguageNotSaved = 700612,
    //    #endregion
    //    //
    //    SimpleWalletCreationSuccess = 174,
    //    SimpleWalletCreationUnSuccess = 175,
    //    AccountRelationshipAddSuccess = 176,
    //    AccountRelationshipAddFailed = 177,
    //    AccountRelationshipDeleteSuccess = 178,
    //    AccountRelationshipDeleteFailed = 179,
    //    SearchDMSDetailsSuccess = 180,
    //    SearchDMSDetailsFailed = 181,
    //    CustomerDataUpdateSuccess = 182,
    //    CustomerDataUpdateFailed = 183,
    //    IMPSTransactionUpdateSuccess = 184,
    //    IMPSTransactionUpdateFailed = 185,
    //    UserAlreadyExist = 186,
    //    CustomerDetailsSuccessful = 187,
    //    CustomerDetailsFailed = 188,
    //    AccountDetailsSuccessful = 189,
    //    AccountDetailsFailed = 190,
    //    EmailSendSuccessfully = 191,
    //    EmailSendFailed = 192,
    //    ServiceReqChargesSuccessful = 193,
    //    ServiceReqChargesFailed = 194,
    //    EsbOtpGenerationSuccessful = 197,
    //    EsbOtpGenerationFailed = 198,
    //    EsbOtpVerifySuccessful = 199,
    //    EsbOtpVerifyFailed = 200,
    //    EsbEsbSMSTemplateSuccessful = 201,
    //    EsbEsbSMSTemplateFailed = 202,
    //    OperatorandPlanDetailsFetchSuccessful = 203,
    //    OperatorandPlanDetailsFetchFailed = 204,
    //    MasterDataFound = 205,
    //    MasterDataCouldNotFound = 206,
    //    TransactionProfileDetailsSuccessful = 207,
    //    TransactionProfileDetailsFailed = 208,
    //    MasterVersionReturnSuccessFul = 209,
    //    MasterVersionReturnFailed = 210,
    //    MasterCacheResetSuccessful = 211,
    //    MasterCacheResetfailed = 212,
    //    GetGLAccountBalanceSuccess = 215,
    //    GetGLAccountBalanceFailed = 216,
    //    RemoveAccountRestrictionSuccess = 217,
    //    RemoveAccountRestrictionFailed = 218,
    //    GetTransactionAuthProfileSuccess = 219,
    //    GetTransactionAuthProfileFailed = 220,
    //    UserUnlockSuccess = 221,
    //    UserUnlockFailed = 222,
    //    //UnBlockUser
    //    UnblockAuthFailed = 800,
    //    UnblockUserSuccess = 801,
    //    UnblockUserFailed = 802,
    //    UnblockUserAlreadyActive = 803,
    //    UnblockUnabletoProcess = 804,
    //    UnblockRequestError = 805,
    //    UnblockUserFound = 806,
    //    UnblockUserR1NotFound = 807,
    //    UnblockUserPasswordChangedSuccess = 810,
    //    UnblockUserMerchantDeviceNotAllowed = 815,
    //    UnblockUserMerchantPANDoesnotMatch = 818,
    //    UnblockUserMerchantDOBDoesnotMatch = 819,
    //    UnblockUserMerchantDOBandPANDoesnotMatch = 820,
    //    UnblockUserMerchantPANNotFound = 823,
    //    UnblockUserMerchantContacthelpdesk = 824,
    //    UnblockUserMerchantExceedsLoginLimit = 825,
    //    //End-UnBlockUser
    //    setMobileBankingPINSuccess = 223,
    //    setMobileBankingPINFailed = 224,
    //    RegisterMBCustomerSuccess = 225,
    //    RegisterMBCustomerFailed = 226,
    //    changemobilebankingpinsuccess = 227,
    //    changemobilebankingpinfailed = 228,
    //    GetSecretQuestionSuccess = 229,
    //    GetSecretQuestionFailed = 230,
    //    UpdateSecretQuestionSuccess = 231,
    //    UpdateSecretFailed = 232,
    //    SetMerchantStatusSuccess = 641,
    //    SetMerchantStatusFailed = 642,
    //    GetMerchantStatusSuccess = 643,
    //    GetMerchantStatusFailed = 644,
    //    ValidUserSuccess = 235,
    //    ValidUserFailed = 236,
    //    EncryptedKeySuccess = 237,
    //    EmcryptedKeyFailed = 238,
    //    BillPaymentTransactionFailed = 252,
    //    BillPaymentTransactionSuccess = 253,
    //    BillPayTransactioninProcesskindlycheckministatement = 615,
    //    RechargeTransactioninProcesskindlycheckministatement = 616,
    //    ValidateUserSecretQuestionSuccess = 254,
    //    ValidateUserSecretQuestionFailed = 255,
    //    RechargeTransactionFailed = 266,
    //    RechargeTransactionSuccess = 267,
    //    PasswordResetSuccess = 270,
    //    PasswordResetFailed = 271,
    //    PasswordChangeSuccess = 272,
    //    PasswordChangeFailed = 273,
    //    SecretQuestionListSuccess = 274,
    //    SecretQuestionListFailed = 275,
    //    ExtraBeneficiaryDetailsFound = 213,
    //    ExtraBeneficiaryDetailsNotFound = 214,
    //    InvalidRequest = 215,
    //    GLAccountBalanceDetailsFound = 256,
    //    GLAccountBalanceDetailsNotFound = 257,
    //    //BillPaymentTransactionFailed = 252,
    //    //BillPaymentTransactionSuccess = 253,
    //    InterBankTransferSuccess = 264,
    //    InterBankTransferFailed = 265,
    //    //RechargeTransactionFailed = 266,
    //    //RechargeTransactionSuccess = 267,
    //    RemitanceAccountOpeningSuccess = 268,
    //    RemitanceAccountOpeningFailed = 269,
    //    InsurancePremiumPaidSuccessful = 298,
    //    InsurancePremiumPaidFailed = 299,
    //    InsuranceClaimSuccessful = 613,
    //    InsuranceClaimFailed = 614,
    //    PrintFormatDataFound = 743,
    //    PrintFormatDataNotFound = 744,
    //    ResetPrintFormatMasterDataSuccess = 745,
    //    ResetPrintFormatMasterDataFailed = 746,

    //    GetExternalAccountDetailsSuccessful = 600,
    //    GetExternalAccountDetailsFailed = 601,
    //    BeneVerificationChargesSuccess = 300,
    //    BeneVerificationChargesFailed = 301,
    //    SequenceListReturnSuccessful = 278,
    //    SequenceListReturnfailed = 279,
    //    TabControlsReturnSuccessFul = 280,
    //    TabControlsReturnFailed = 281,
    //    CreateCustomerWalletSuccess = 282,
    //    CreateCustomerWalletFailed = 283,
    //    FindCustomerSuccess = 284,
    //    FindCustomerFailed = 285,
    //    AuthProfileSuccess = 286,
    //    AuthProfileFailed = 287,
    //    AuthenticateSuccesss = 288,
    //    AuthenticateFailed = 289,
    //    PublicKeySendSuccess = 290,
    //    PublicKeySendFailed = 291,
    //    MenuListByChannelSentSuccess = 292,
    //    MenuListByChannelFailed = 293,
    //    ProfileTypeTransByChannelSuccess = 294,
    //    ProfileTypeTransByChannelFailed = 295,
    //    ProductTransByChannelSuccess = 296,
    //    ProductTransByChannelFailed = 297,

    //    ProductWiseTransactionListSuccess = 302,
    //    ProductWiseTransactionListFailed = 303,
    //    BeneUpdateSuccess = 304,
    //    BeneUpdateFailed = 305,
    //    WalkInCustomerDetailsSuccess = 306,
    //    WalkInCustomerDetailsFailed = 307,
    //    WalkInTransactionDetailsSuccess = 308,
    //    WalkInTransactionDetailsFailed = 309,
    //    AccountLimitDetailsSuccess = 310,
    //    AccountLimitDetailsFailed = 311,
    //    SupervisiorDetailsSuccess = 312,
    //    SupervisiorDetailsFailed = 313,
    //    AccountRestrictionInfoSuccess = 314,
    //    AccountRestrictionInfoFailed = 315,
    //    AccountOpeningRequestDetailsSuccess = 362,
    //    AccountOpeningRequestDetailsFailed = 363,
    //    AccountOpeningEsignSuccess = 715,
    //    AccountOpeningEsignFailed = 716,
    //    AccountDetailsSuccess = 617,
    //    AccountDetailsFail = 618,
    //    DebitkitDetailsSuccess = 629,
    //    DebitKitdetailsFailed = 630,
    //    ServiceRequestCountSuccess = 633,
    //    ServiceRequestCountFailed = 634,
    //    LMSAccountBalHoldInfoSuccess = 377,
    //    LMSAccountBalHoldInfoFailed = 378,
    //    BeneVerificationSuccess = 316,
    //    BeneVerificationFailed = 317,
    //    UserDetailSuccess = 318,
    //    UserDetailUnSuccess = 319,
    //    ResetMenuCacheSuccessful = 320,
    //    ResetMenuCacheFailed = 321,
    //    ResetProfileSuccessful = 322,
    //    ResetProfileFailed = 323,
    //    FavouriteTransactionSuccessful = 324,
    //    FavouriteTransactionFailed = 325,
    //    GetAccountStatementSuccessful = 326,
    //    GetAccountStatementFaliled = 327,
    //    ManagementHealthAPIsuccessful = 328,
    //    UpdateKitStatussuccessfull = 329,
    //    UpdateKitStatusUnsuccessfull = 330,
    //    WelcomeKITAcknowlegementStatusSuccess = 741,
    //    WelcomeKITAcknowlegementStatusFailed = 742,
    //    DMSGetAccountStatusSuccess = 821,
    //    DMSGetAccountStatusFailed = 822,
    //    DMSAdharVaultStatusSuccess = 836,
    //    DMSAdharVaultStatusFailed = 837,
    //    GetWorkingAddressSuccess = 842,
    //    GetWorkingAddressFailed = 843,
    //    GetForm60StatusSuccess = 844,
    //    GetForm60StatusFailed = 845,
    //    GetAadhaarLinkStatusSuccess = 846,
    //    GetAadhaarLinkStatusFailed = 847,
    //    GetAdharSeedingEnquirySuccess = 870,
    //    GetAdharSeedingEnquiryFailed = 871,
    //    GetDMSMobileDedupeSuccess = 872,
    //    GetDMSMobileDedupeFailed = 873,
    //    Branchreportsuccess = 331,
    //    Branchreportfailed = 332,
    //    Branchchannelreportsuccess = 333,
    //    Branchchannelreportfailed = 334,
    //    BranchProductreportsuccess = 335,
    //    BranchProductreportfailed = 336,
    //    BranchTranstypereportsuccess = 337,
    //    BranchTranstypereportfailed = 338,
    //    Channelreportsuccess = 339,
    //    Channelreportfailed = 340,
    //    ChannelProductreportsuccess = 341,
    //    ChannelProductreportfailed = 342,
    //    ChannelTranstypereportsuccess = 343,
    //    ChannelTranstypereportfailed = 344,
    //    Customerreportsuccess = 345,
    //    Customerreportfailed = 346,
    //    Productreportsuccess = 347,
    //    Productreporfailed = 348,
    //    Transtypereportsuccess = 349,
    //    Transtypereportfailed = 350,
    //    Userreportsuccess = 351,
    //    Userreportfailed = 352,
    //    UserProductreportsuccess = 353,
    //    UserProductreportfailed = 354,
    //    UserTranstypereportsuccess = 355,
    //    UserTranstypereportfailed = 356,
    //    TransListreportsuccess = 357,
    //    TransListreportfailed = 358,
    //    Ministatementreportsuccess = 359,
    //    Ministatementreportfailed = 360,
    //    UserWiseProductListSuccess = 361,
    //    UserWiseProductListFailed = 362,
    //    ServiceRequestStatusSuccess = 363,
    //    ServiceRequestStatusFailed = 364,
    //    CashCollectionVerificationSuccessful = 365,
    //    CashCollectionVerificationFailed = 366,
    //    CashCollectionTransactionSuccessful = 611,
    //    CashCollectionTransactionFailed = 612,
    //    CashCollectionAdhaarValidationSuccessful = 649,
    //    CashCollectionAdhaarValidationFailed = 650,
    //    SupervisorUserDetailsSuccess = 371,
    //    SupervisorUserDetailsFailed = 372,
    //    LockUserDetailsSuccess = 373,
    //    LockUserDetailsFailed = 374,
    //    UnLockUserDetailsSuccess = 375,
    //    UnLockUserDetailsFailed = 376,
    //    RemoveAccountRestrictSuccess = 377,
    //    RemoveAccountRestrictFailed = 378,
    //    KeyExchangedSuccessful = 379,
    //    CardTransactionSuccessful = 380,
    //    BalanceEnquirySuccessful = 381,
    //    cardtransactionBalanceEnquiryFailed = 604,
    //    CardTransactioncashwithdrawalFailed = 605,
    //    KeyExchangedFailed = 606,
    //    SetCardPinSuccessfull = 382,
    //    Invaliduserid = 912,
    //    InvalidTerminal = 913,
    //    Transactionfailed = 914,

    //    verifyTPINSuccess = 403,
    //    verifyTPINFailed = 404,
    //    GetclosureAmountSuccess = 405,
    //    GetclosureAmountFailed = 406,

    //    EJLogsSuccess = 700540,
    //    EJLogsFailure = 700541,

    //    Croselfaild = 747,
    //    Croselsucess = 748,

    //    AccountRistrictionSuccess = 700615,
    //    AccountRistrictionFailed = 700616,
    //    // Customer Grievance Data Get mesages
    //    CustomerGrievanceDataGetFailed = 603,
    //    CustomerGrievanceDataGetSuccessful = 602,
    //    TrackSuryesSuccess = 635,
    //    TrackSurveysFailed = 636,
    //    AccountCheckSuccess = 637,
    //    AccountCheckFailed = 638,
    //    DMSChequeIssuanceValidationSuccess = 811,
    //    DMSChequeIssuanceValidationFailed = 812,
    //    DMSChequeIssuanceAPISuccess = 813,
    //    DMSChequeIssuanceAPIFailed = 814,
    //    DMSKitRequestSuccess = 697,
    //    DMSKitRequestFailed = 698,
    //    DMSKitStatusUpdatedSuccess = 647,
    //    DMSKitStatusUpdatedFailed = 648,
    //    DMSKitSearchSuccess = 701,
    //    DMSKitSearchFailed = 702,
    //    UpdateSISuccess = 651,
    //    UpdateSIFailed = 652,
    //    ViewSIListSuccess = 653,
    //    ViewSIListFailed = 654,
    //    CreateSIRequestSuccess = 655,
    //    CreateSIRequestFailed = 656,
    //    DeleteSISuccess = 657,
    //    DeleteSIFailed = 658,
    //    TagDetailsSuccess = 707,
    //    TagDetailFailed = 708,
    //    TagDetailsGetSuccess = 709,
    //    TagDetailsGetFailed = 710,
    //    IFTFileApprovedSuccess = 717,
    //    IFTFileApprovedFailed = 718,
    //    GetFileDetailsSuccess = 719,
    //    GetFileDetailsFailed = 720,
    //    GetCheckerDashboardDataSuccess = 747,
    //    GetCheckerDashboardDataFailed = 748,
    //    GetApproverDashboardDataSuccess = 749,
    //    GetApproverDashboardDataFailed = 750,
    //    //DMT PPI Transaction Messages

    //    SearchWalkingCustomersSuccess = 367,
    //    WalkinCustomerLimitSuccess = 368,
    //    WalkinDMTImpsNeftSuccess = 430,
    //    SearchWalkingCustomersFailed = 370,
    //    WalkinCustomerLimitFailed = 371,
    //    WalkinDMTImpsNeftFailed = 431,

    //    //Lending Acc
    //    HHVDownloadSuccess = 434,
    //    HHVDownloadFailed = 435,
    //    CGTUploadSuccess = 436,
    //    CGTUploadFailed = 437,
    //    RCGTUploadSuccess = 438,
    //    RCGTUploadFailed = 439,
    //    SaralHHVUploadSuccess = 440,
    //    SaralHHVUploadfailed = 441,
    //    LUCSolarDownloadSuccess = 442,
    //    LUCSolarDownloadFailed = 443,
    //    LUCSolarUploadSuccess = 444,
    //    LUCSolarUploadfailed = 445,
    //    HolidayDemandDownloadSuccess = 446,
    //    HolidayDemandDownloadFailed = 447,
    //    MaturityDemandDownloadSuccess = 448,
    //    MaturityDemandDownloadFailed = 449,
    //    RegularDemandDownloadSuccess = 450,
    //    RegularDemandFailed = 451,
    //    GroupCenterAttendanceSuccess = 452,
    //    GroupCenterAttendanceFailed = 453,
    //    LoanTxnDataSuccess = 454,
    //    LoanTxnDataFailed = 456,
    //    GTRDownLoadwebServiceSuccess = 457,
    //    GTRDownLoadwebServiceFailed = 458,
    //    RECGTDownloadwebServiceSuccess = 459,
    //    RECGTDownloadwebServiceFailed = 460,
    //    HHVDownLoadwebServiceSuccess = 461,
    //    HHVDownLoadwebServiceFailed = 462,
    //    GRTUploadDataSuccess = 471,
    //    GRTUploadDataFailed = 472,
    //    CreditinquiryServiceSuccess = 473,
    //    CreditinquiryServiceFailed = 474,
    //    AdvanceNForeClosureSuccess = 475,
    //    AdvanceNForeClosureFailed = 476,
    //    ESBCustomSearchSuccess = 477,
    //    ESBCustomSearchFailed = 478,
    //    GetCenterGroupDataSuccess = 479,
    //    GetCenterGroupDataFailed = 480,
    //    DisbursementCustomersDataSuccess = 481,
    //    DisbursementCustomersDataFailed = 482,
    //    GetEnrollmentDetailSuccess = 483,
    //    GetEnrollmentDetailFailed = 484,
    //    PostcustomerDisbursementSuccess = 485,
    //    PostcustomerDisbursementFailed = 486,
    //    Esb25LegTransactionRepaySuccess = 487,
    //    Esb25LegTransactionRepayFailed = 488,
    //    EsbHOApprovalSuccess = 489,
    //    EsbHOApprovalFailed = 490,
    //    EsbProbableCenterDownloadSuccess = 491,
    //    EsbProbableCenterDownloadFailed = 492,
    //    EsbAdvanceAndForeClosureSuccess = 515,
    //    EsbAdvanceAndForeClosureFailed = 516,
    //    EsbTransactionUpdateHoverSuccess = 517,
    //    EsbTransactionUpdateHoverFailed = 518,
    //    EsbTransactionRepaymentHoverSuccess = 519,
    //    EsbTransactionRepaymentHoverFailed = 520,
    //    EsbEODCompletionSuccess = 521,
    //    EsbEODCompletionFailed = 522,
    //    CardStatusUpdateSuscess = 509,
    //    CardStatusUpdateFailed = 510,
    //    CardIssuanceSuccess = 511,
    //    CardIssuanceFailed = 512,

    //    JayamMMiniStmtSuccess = 639,
    //    JayamMiniStmtFailed = 640,
    //    RivigoDisbursementSuccess = 645,
    //    RivigoDisbursementFailed = 646,
    //    UserSurveySuccess = 659,
    //    UserSurveyFailed = 660,
    //    JayamEnrollmentAccountOpeningSuccess = 665,
    //    JayamEnrollmentAccountOpeningFailed = 666,

    //    #region Fast Tag
    //    FasttagVehicleregSucessful = 669,
    //    FasttagVehicleregFailed = 670,
    //    FasttagregistrationdetailsFound = 671,
    //    FasttagregistrationdetailsnotFound = 673,

    //    FastagBarcodeMappingSuccessful = 8012,
    //    FastagBarcodeMappingFailed = 8013,
    //    registeredVehicleStatusSuccessful = 8014,
    //    registeredVehicleStatusFailed = 8015,
    //    BpayPrefilledVehicleDetailssuccess = 8016,
    //    BpayPrefilledVehicleDetailsFailed = 8017,
    //    BpayRegistrationDeletionSucessful = 8018,
    //    BpayRegistrationDeletionfailed = 8019,



    //    VehicleTagIssuranceSuccessful = 675,
    //    VehicleTagIssuranceFailed = 676,
    //    VehiclePostTransactionSuccessful = 674,
    //    VehiclePostTransactionFailed = 672,
    //    VehicleVerificationCodeSuccessful = 679,
    //    VehicleVarificationCodeFailed = 680,

    //    VerificationCodeSendSucessfully = 681,
    //    VerificationCodeSendFailed = 682,

    //    TagblockSucessfully = 685,
    //    TagblockFailed = 686,
    //    TagUnblockSucessfully = 687,
    //    TagUnblockFailed = 688,
    //    DMSTagVerificationSuccessful = 689,
    //    DMSTagVerificationFailed = 690,

    //    ExceptionAmountSuccessful = 691,
    //    ExceptionAmountFailed = 692,

    //    TagCloseSucessful = 693,
    //    TagCloseFailed = 694,

    //    TagReissuanceSucessful = 699,
    //    TagReissuanceFailed = 700,

    //    GetTransactionDetailsSuccessful = 711,
    //    GetTransactionDetailsFailed = 712,

    //    UpdateCBSStatusSuccess = 713,
    //    UpdateCBSStatusFailed = 714,
    //    FasttaInvalidRequest = 1371,
    //    FasttaInvalidVehicleDetails = 1372,
    //    FasttagWalletisalreadyOpen = 1373,
    //    Fasttagcustcustomeraccountdetailfailed = 1374,
    //    Fasttagvehiclisblacklist = 1375,
    //    FasttagUnabletoconnectremotserver = 1376,
    //    FasttagMinistatment = 1377,
    //    FasttagVehiclealredyregister = 1378,
    //    FasttagVehiclealnotregister = 1379,
    //    FasttagUPADetailFound = 1380,
    //    FasttagUPADetailnotFound = 1381,
    //    FasttagDetailnotFound = 1382,
    //    FasttagServernotresponding = 1383,
    //    Fasttagupaaccnoupdatesuccess = 1384,
    //    Fasttagupaaccnoupdatefailed = 1385,
    //    Fasttagvirtualaddnotfound = 1386,
    //    FasttagSuccess = 1387,
    //    FasttagFailed = 1388,
    //    FasttagRecordnotfound = 1389,
    //    FasttagVehicletypeupdatesucessfully = 1390,
    //    FasttagVehicletypeupdatefailed = 1391,
    //    FasttagOTPverifyfailed = 1393,
    //    FasttagFPverifyfailed = 1394,
    //    Fasttagotpexpired = 1395,
    //    Fasttagverifycodesucess = 1396,
    //    Fasttagverifycodefailed = 1397,
    //    Fasttaginternalservererror = 1398,
    //    Fasttagverifycodesucessti = 1399,
    //    Fasttagverifycodefailedti = 1400,


    //    #endregion

    //    GetIINMasterDataSuccess = 735,
    //    GetIINMasterDataFailed = 736,

    //    ResetIINMasterDataSuccess = 737,
    //    ResetIINMasterDataFailed = 738,

    //    #region CashProcess message
    //    CashProcessUserDetailsSuccess = 407,
    //    CashProcessUserDetailsFailed = 408,
    //    CashProcessVaultDetailsSuccess = 409,
    //    CashProcessVaultDetailsFailed = 410,
    //    CashProcessVaultBalanceSuccess = 413,
    //    CashProcessVaultBalanceFailed = 414,
    //    EodProcessUserdetailsSuccess = 625,
    //    EodUserDetailsFailed = 626,
    //    EodProcessTransactionSuccess = 627,
    //    EodProcessTransactionFailed = 628,
    //    EodBranchcloseProcessSuccess = 631,
    //    EodBranchcloseProcessFailed = 632,
    //    EodUserDetailsfailed = 918,
    //    CBSPostingGetUserDtailsSuccess = 725,
    //    CBSPostingGetUserDtailsFailed = 726,
    //    CBSPostTransactionSuccess = 727,
    //    CBSPostTransactionFailed = 728,
    //    DMSTrackRevisionSuccess = 729,
    //    DMSTrackRevisionFailed = 730,

    //    #endregion

    //    #region Reversal Transaction
    //    ReversalTransactionSuccess = 411,
    //    ReversalTransactionFailed = 412,
    //    #endregion
    //    #region Bucket
    //    UpdateBucketBalanceSuccess = 415,
    //    UpdateBucketBalanceFailed = 416,
    //    #endregion

    //    #region AEPS transaction
    //    AEPStransactionSuccess = 417,
    //    AEPSTransactionFailed = 418,
    //    AEPSBalanceEnquirySuccess = 424,
    //    AEPSBalanceEnquiryFailed = 427,
    //    #endregion

    //    #region Petty Transaction
    //    PettyCashDepositSuccess = 419,
    //    PettyCashDepositFailed = 420,
    //    PettyCashWithdrawSuccess = 421,
    //    PettyCashWithdrawFailed = 422,
    //    PettyGlBalanceSuccess = 423,
    //    PettyGlBalanceFailed = 426,
    //    PettyLimitexpense = 917,
    //    #endregion


    //    #region Reversal Transaction
    //    CashOutTransactionSuccess = 428,
    //    CashOutTransactionFailed = 429,
    //    #endregion

    //    #region Maker Checker Message
    //    GetMakerSuccess = 493,
    //    GetMakerFailed = 494,
    //    GetCheckerSuccess = 495,
    //    GetCheckerFailed = 496,
    //    MakerPostSuccess = 497,
    //    MakerPostFailed = 498,
    //    MakerCancelSuccess = 499,
    //    MakerCancelFailed = 500,
    //    CheckerApprovedSuccess = 501,
    //    CheckerApprovedFailed = 502,
    //    CheckerRejectSuccess = 503,
    //    CheckerRejectFailed = 504,
    //    #endregion

    //    #region IMPS/NEFT
    //    IMPSTransactionSuccess = 607,
    //    IMPSTransactionFailed = 608,
    //    NEFTTransactionSuccess = 609,
    //    NEFTTranscationFailed = 610,
    //    #endregion

    //    #region RTGS
    //    RTGSChargesSuccess = 505,
    //    RTGSChargesFailed = 506,
    //    RTGSTransactionSuccess = 507,
    //    RTGSTransactionFailed = 508,
    //    #endregion RTGS

    //    #region CDM

    //    CDMVerificationFailed = 622,
    //    CDMTransactionFailed = 620,

    //    #endregion
    //    #region Shopkeeper Policy Insurance
    //    IPRUShubrakshaFetchDetailsFailed = 739,
    //    IPRUShubrakshaFetchDetailsSuccessfully = 740,
    //    #endregion

    //    #region Shopkeeper Policy Insurance

    //    ShopkeeperPolicyFetchDetailsSuccessfully = 661,
    //    ShopkeeperPolicyFetchDetailsFailed = 662,
    //    ShopkeeperPolicyUpdateDetailsSuccessfully = 663,
    //    ShopkeeperPolicyUpdateDetailsFailed = 664,

    //    #endregion

    //    #region Hospicash Policy Insurance

    //    HospicashPolicyFetchDetailsSuccessfully = 667,
    //    HospicashPolicyFetchDetailsFailed = 668,
    //    HospicashPolicyFetchUHIDStatusDetailsSuccessfully = 677,
    //    HospicashPolicyFetchUHIDStatusDetailsFailed = 678,

    //    #endregion

    //    #region Lombard Two Wheeler

    //    TWMasterDetailsFetchSuccessfully = 721,
    //    TWMasterDetailsFetchFailed = 722,
    //    TWQuoteGenerationSuccessfully = 723,
    //    TWQuoteGenerationFailed = 724,

    //    #endregion

    //    #region Last Action Lead Form

    //    LastActionLeadFormSuccess = 683,
    //    LastActionLeadFormFailed = 684,

    //    #endregion

    //    CIFKYCDetailsSuccess = 695,
    //    CIFKYCDetailsFailed = 696,
    //    SearchAgentSuccess = 703,
    //    SearchAgentFailed = 704,
    //    UpdateAgentSuccess = 705,
    //    UpdateAgentFailed = 706,
    //    //Max Id (706)
    //    #region RMF
    //    RMFFolioFailed = 700532,
    //    RMFFolioSuccess = 700533,
    //    RMFTxnSuccess = 700534,
    //    RMFTxnFailed = 700535,
    //    RMFSchemeDetailsSuccess = 700536,
    //    RMFSchemeDetailsFailed = 700537,
    //    RMFRedemptionSuccess = 700538,
    //    RMFRedemptionFailed = 700539,
    //    #endregion RMF

    //    GLZeroizationSuccess = 816,
    //    GLZeroizationFailed = 817,
    //    TransactionReporst_StatementSRTaken = 826,
    //    TransactionReporst_StatementSRUnabletoProcess = 827,
    //    TransactionReporst_StatementSREmailVerifyLinkSent = 828,
    //    TransactionReporst_StatementSREmailVerifyLinkSentFailed = 829,
    //    TransactionReporst_StatementSREmailUpdationFailed = 830,
    //    TransactionReporst_StatementSREmailNotUpdated = 831,
    //    TransactionReporst_StatementSREmailVerified = 832,
    //    TransactionReporst_StatementSREmailVPending = 833,
    //    TransactionReporst_StatementSREmailUpdatedSuccess = 834,
    //    TransactionReporst_StatementSREmailVerifyLinkExpired = 835,
    //    TransactionReporst_StatementSREmailAlredyVerified = 838,
    //    TransactionReporst_StatementSRInvalid = 839,


    //    #region "Cashin bank"

    //    Cashinbanklocationfound = 8007,
    //    Cashinbanklocationnotfound = 8008,

    //    CashinbankImagefound = 8009,
    //    CashinbankImagenotfound = 8010,
    //    CashinbankInvalidRequest = 8011,

    //    #endregion

    //    #region "Digital Passbook"
    //    DigitalPassbookSuccess = 700542,
    //    DigitalPassbookFailed = 700543,
    //    DigitalPassbookPDFFailed = 700544,
    //    #endregion


    //    #region "Sms Details"
    //    SmsDetailskSuccess = 800702,
    //    SmsDetailsFailed = 800703,
    //    #endregion

    //    #region "Suryoday Account Close"
    //    SuryodayAcnCloseSuccess = 840,
    //    SuryodayAcnCloseFail = 841,
    //    #endregion

    //    #region "Cash in Match data"

    //    CashInInsertBankStnmtSuccess = 848,
    //    CashInInsertBankStnmtFailuer = 849,

    //    CashInMatchBankStnmtSuccess = 850,
    //    CashInMatchBankStnmtFailuer = 851,

    //    CashInUpdateBankStnmtSuccess = 852,
    //    CashInUpdateBankStnmtFailuer = 853,

    //    CashInViewBankStnmtSuccess = 854,
    //    CashInBankStnmtFileFailuer = 855,
    //    CashInBankStnmtMatchBalanceFailuer = 856,

    //    #endregion
    //    #region ReferalLoan
    //    ReferalLoanVerificationSuccess = 857,
    //    ReferalLoanVerificationFailed = 858,

    //    #endregion

    //    #region merchant payouts
    //    GetPayoutdata = 857,
    //    GetPayoutdataFailure = 858,
    //    #endregion

    //    #region self declared kits
    //    GetSelfdeclaredkitdata = 859,
    //    GetSelfdeclaredkitdataFailure = 860,
    //    Selfdeclaredkitsave = 861,
    //    SelfdeclaredkitsaveFailure = 862,
    //    GetKitdataapproval = 863,
    //    GetKitdataapprovalFailure = 864,
    //    Approvekitdata = 865,
    //    ApprovekitdataFailure = 866,

    //    #endregion
    //    PincodeValidateSuccess = 867,
    //    PincodeValidateFailedWithRestriction = 868,
    //    PincodeValidateFailed = 869,

    //    #region bbps cust comp 1846
    //    checkbbpscomplaintstatusSuccess = 876,
    //    checkbbpscomplaintstatusFailed = 877,

    //    checkbbpscomplaintdataSuccess = 878,
    //    checkbbpscomplaintdataFailed = 879,

    //    SubmitbbpscomplaintdataSuccess = 874,
    //    SubmitbbpscomplaintdataFailed = 875,
    //    #endregion

    //    #region Foreign Remittance
    //    AgentCreationSuccess = 1600,
    //    AgentCreationFailed = 1601,

    //    FRTransactionSuccess = 1602,
    //    FRTransactionFailed = 1603,

    //    FRGetTransactionSuccess = 1604,
    //    FRGetTransactionFailed = 1605,

    //    FRJVVerificationSuccess = 1606,
    //    FRJVVerificationFailed = 1607,

    //    FRMasterdataSuccess = 1608,
    //    FRMasterdataFailed = 1609,

    //    FRAgentSuccess = 1610,
    //    FRAgentFailed = 1611,

    //    FRUpdateagentSuccess = 1612,
    //    FRUpdateagentFailed = 1613,

    //    FRRevisiondataSuccess = 1614,
    //    FRRevisiondataFailed = 1615,

    //    FRRevisionSuccess = 1616,
    //    FRRevisionFailed = 1617,

    //    FRDocDmsSuccess = 1618,
    //    FRDocDmsFailed = 1619,

    //    FRAckPdfSuccess = 1620,
    //    FRAckPdfFailed = 1621,

    //    FRCAReportPdfSuccess = 1622,
    //    FRCAReportPdfFailed = 1623,

    //    FRMerAgreementSuccess = 1624,
    //    FRMerAgreementFailed = 1625,
    //    #endregion


    //    PanUpdateInCBsSuccess = 2001,
    //    PanUpdateInCBSFailed = 2002,

    //    AccountClosureChargesSuccess = 904,
    //    AccountClosureChargesFailed = 905,

    //    DMSGuardianNumberFound = 1001,
    //    DMSGuardianNumberNotFound = 1002,
    //    LatLongUpdateSuccessfully = 1003,
    //    LatLongUpdateFailed = 1004,
    //    DMSSRCounterSuccess = 1005,
    //    DMSSRCounterFailed = 1006,
    //    ITRStatusSuccess = 906,
    //    ITRStatusFailed = 907,
    //    #region CustomerSupport
    //    custSupportSuccess = 908,
    //    custSupportFailed = 909,
    //    #endregion

    //    #region ForBillPayService
    //    FingerPrintAuthenFailed = 910,
    //    AadharAuthenFailed = 911,
    //    operationtimeOutMiniStatement = 915,
    //    operationtimeOut = 916,
    //    #endregion
    //    #region Insurance
    //    InsurancePremiumMismatch = 1111,
    //    InsuranceInvalidBadRequest = 1112,
    //    InsuranceBuildLatestVr = 1113,
    //    InsuranceOVDDetails = 1114,
    //    InsuranceCloseExternalAccFalied = 1115,
    //    InsuranceOtpAuthFailed = 1116,
    //    InsuranceFPverificationFalied = 1117,
    //    InsuranceTranTypeMismatch = 1118,
    //    #endregion


    //    #region FPBFinancial RestService
    //    AccountOverrideChargesSuccess = 1111,
    //    AccountOverrideChargesFailed = 1112,
    //    AnalysisFlagIs1 = 1113,
    //    InvalidErrorTxnLimitService = 1114,
    //    TxnLimitDetailsNotAvailable = 1115,
    //    UnableToParseTxnLimitRequest = 1116,
    //    InvalidErrorInGetAccountOverrideChargesAPI = 1117,
    //    ChargeOverrideDetailsNotAvailable = 1118,
    //    UnableToParseChargeOverrideRequest = 1119,
    //    TxnNotAllowedForSelectedProduct = 1120,
    //    TransactionAllowed = 1121,
    //    InvalidErrorInRestrictTxnByProductService = 1122,
    //    UnableToParseRequestData = 1123,
    //    #endregion

    //    #region BusinessLogic TransactionLimit Contract
    //    TxnLimitExceededTransactionFailed = 1124,
    //    Success = 1125,
    //    TxnLimitsDetailsNotFound = 1126,
    //    RecordNotFound = 1127,
    //    UnableToPerformTxnnCustomerNotExists = 1128,
    //    OverrideChargesCalculationFailed = 1129,
    //    OverrideConditionNotMatchedFetchChargesFromFIS = 1130,
    //    OverrideChargesNotConfigured = 1131,
    //    AccountChargesOverrideDetailsNotFound = 1132,
    //    TxnNotAllowedForWallet = 1133,
    //    #endregion

    //    #region FPBNonFinancial RestService
    //    UserNotAuthorizedToProceedTransaction = 1134,
    //    NEFTTransactionNotAllowed = 1135,
    //    BeneIFSCOrAccNumberCannotBeNullorEmpty = 1136,
    //    Mobilenumbershouldnotbenullorempty = 1137,
    //    TxnDetailsNotAvailableRequestData = 1138,
    //    WalkinTransaction = 1139,
    //    TxnTypeNotConfiguredForRestrictionProductCode = 1140,
    //    ProductCodeNotConfigured = 1370,
    //    #endregion

    //    #region BusinessLogic NonFinancial Contract
    //    NotalwdprfrmCshnaprvl = 1141,
    //    trnsctnbtwnctoftime = 1142,
    //    DearCstmrAplgsincnvnceplstrysvcaftr = 1143,
    //    Rcrdnotfndfr = 1144,
    //    Unbletofndcutoftime = 1145,
    //    PostTrnsctnnotfound = 1146,
    //    #endregion


    //    TxnUnderProccessCheckMiniStatment = 1147,
    //    AccountClosureFnctnltyNotApplicableWlts = 1148,
    //    ChannelIDNotFound = 1149,
    //    UserClassNotFound = 1150,
    //    ProductTypeNotFound = 1151,
    //    DearCustomerFunctionalityInoperativeBtwnCutOffTime = 1152,
    //    TxnDeclinedDueCreditRestrictionAccount = 1153,
    //    CASAPLUSViewBlnceFailed = 1154,
    //    TxnAmountMustLessMerchantLimit = 1155,
    //    InvalidAccountNumber = 1156,
    //    TxnNotAllowed = 1157,
    //    CustomerConsumeLimitFound = 1158,
    //    CustomerConsumeLimitNotFound = 1159,
    //    CashWithdrawlTxnLimitDtlsNotFoundUser = 1160,
    //    ServiceNotRespondingException = 1161,
    //    InvalidMerchantDetails = 1162,
    //    DearMerchantContactBranchOrSalesOfficerForSupport = 1163,
    //    RequestDataNotFound = 1164,
    //    MerchentLimitSuccess = 1165,
    //    MerchentLimitFail = 1166,
    //    GetMerchantLimitFailed = 1167,
    //    MerchantNotAsCustomer = 1168,
    //    AccountDetailsNotFound = 1169,
    //    NotalwdtoprfrmCshnaprvl = 1170,
    //    CutOffTimeFndCstmrSuccess = 1171,
    //    Acntnbrprdctcdnomtchdinfndcstmr = 1172,
    //    Cstmracntisinvld = 1173,
    //    //InvalidRequest = 1174,
    //    UnableProcceedTxnPleaseTryAagain = 1175,
    //    SuccessfullyInserted = 1176,
    //    YourRequestHasSubmittedSuccessfully = 1177,
    //    FailedToInsert = 1178,
    //    AlertNameAlreadyPresent = 1179,
    //    MerchantNotifictionDetailsSuccess = 1180,
    //    NoNewMessage = 1181,
    //    ServerNotRespondingPleaseTryAgainLater = 1182,
    //    RemoteServerReturnedError = 1183,
    //    AutoTxnChargesRequest = 1184,
    //    Banknameshuldnotbeempty = 1185,
    //    UnablePerformTxnDueIMPSNotAllowedSelectedBank = 1186,
    //    ForslctdbankIMPSNEFTtrnsctnnotallowed = 1187,
    //    UnblprfrmtrnsctndueTrnsctntypeshuldnotnley = 1188,
    //    AutoTxnSuccess = 1189,
    //    AutoTxnFailed = 1190,
    //    ErrorInSystemWhileApproving = 1191,
    //    GLAccountNumberNotFound = 1192,
    //    LimitApprovedSuccessfully = 1193,
    //    RequestedLimitCancelled = 1194,
    //    RecordExistsInCBS = 1195,
    //    RecordNotExistsInCBS = 1196,
    //    ApproveStatusUpdated = 1197,
    //    ErrorUpdatingApproved = 1198,
    //    MerchantNameNotFound = 1199,
    //    NoRecordFound = 1200,
    //    DuplicateRqustNumber = 1201,
    //    ModeOfTxnDataFound = 1202,
    //    BankDataFound = 1203,
    //    BankDataNotFound = 1204,
    //    DataFound = 1205,
    //    CashInIntntCountFound = 1206,
    //    CashInIntntCountNotFound = 1207,
    //    DplcteRqustNmbr = 1208,
    //    CustomerNumberShouldNotNull = 1209,
    //    FngrPrintnotactvtd = 1210,
    //    CustomerFPDataAvailable = 1211,
    //    CustomerFPDataNotExist = 1212,
    //    FngrPrintnotmatched = 1213,
    //    CustomerSupportDetailsuccess = 1214,
    //    CustomerSupportDtlsDataSelectionFailed = 1215,
    //    RequstError = 1216,
    //    Merchantrtinginformation = 1217,
    //    Merchantrtinginformationnotavailable = 1218,
    //    ServiceisRestricted = 1219,
    //    DataNotFound = 1220,
    //    NoDetailsFound = 1221,

    //    RecordNotFoundBLLDB = 1222,
    //    RequestNotContainXCorelationID = 1223,
    //    RequestDataEmpty = 1224,
    //    InvalidJSONTxnResponse = 1225,
    //    TxnResponseNotFound = 1226,
    //    UnableParseResponse = 1227,
    //    TxnDetailsNotFoundThisTxnType = 1229,
    //    AEPSTxnLimitDetailsNotFoundThisUser = 1230,
    //    InvalidUserId = 1231,
    //    InvalidTerminalId = 1232,
    //    BAVVerifiedSuccess = 1233,
    //    AEPSCashDepositTxnFailed = 1234,
    //    AEPSCashDepositSuccess = 1235,
    //    AEPSCashDepositFailed = 1236,
    //    AepsTwoFactorAuthDataInsertSuccess = 1237,
    //    AepsTwoFactorAuthDataInsertFailed = 1238,
    //    ESBServerUnavailable = 1239,
    //    InvalidBadRequestf = 1240,
    //    AEPSMiniStatementFailed = 1241,

    //    #region Rewards
    //    ServerNotRes = 1300,
    //    RewardDataFound = 1301,
    //    RewardDataNotFound = 1302,
    //    ClavaxDataFound = 1305,
    //    ClavaxDataNotFound = 1306,
    //    RewardStmtFound = 1307,
    //    RewardStmtNotFound = 1308,
    //    #endregion

    //    #region Registration
    //    StrCifID = 1320,
    //    StrCifIDNotAvailable = 1321,
    //    SuccessFlag = 1322,
    //    FailedFlag = 1323,
    //    InvalidUserID = 1324,
    //    InvalidTerminalID = 1325,
    //    PanValidationFailedRequest = 1326,
    //    PanValidationFailed_AttemptExceed = 1327,
    //    PanValidationFailed_PanCount = 1328,
    //    PanValidationFailed_signfailed = 1329,
    //    PanValidationFailed_AddressNotFound = 1330,
    //    MerlatLongSuccess = 1331,
    //    MerlatLongFailed = 1332,
    //    RequestdataNotFound = 1333,
    //    AcctNoNotFound = 1334,
    //    EKYCStatusFound = 1335,
    //    EKYCStatusNotFound = 1336,
    //    ReqFormatErr = 1337,
    //    MerStatusUpdate = 1338,
    //    MerStatusUpdateFailed = 1339,
    //    AddProd_pincode = 1340,
    //    AddProd_AllowCust = 1341,
    //    CustDataFound = 1342,
    //    CustDataNotFound = 1343,
    //    #endregion

    //    #region Lic Billpayment
    //    FetchLICBillpaymentDetailSuccess = 1350,
    //    FetchLICBillpaymentDetailFailed = 1351,
    //    FetchLICBillpaymentChargesSuccess = 1352,
    //    FetchLICBillpaymentChargesFailed = 1353,
    //    PostLICBillpaymentTransactionSuccess = 1354,
    //    PostLICBillpaymentTransactionFailed = 1355,
    //    #endregion
    //    #region Cc Billpayment
    //    FetchCcBillpaymentDetailSuccess = 1360,
    //    FetchCcBillpaymentDetailFailed = 1361,
    //    FetchCcBillpaymentChargesSuccess = 1362,
    //    FetchCcBillpaymentChargesFailed = 1363,
    //    PostCcBillpaymentTransactionSuccess = 1364,
    //    PostCcBillpaymentTransactionFailed = 1365,
    //    #endregion
    //    #region CMS Cash Collection
    //    TokenNotGenerated = 700600,
    //    DownloadLatest = 700601,
    //    SuspiciousTransactionDetected = 700602,
    //    AmtMismatch = 700603,
    //    BlankToken = 700604,
    //    MagmaCustValidation = 700613,
    //    #endregion

    //    invalidMapperID = 1401,

    //    #region CMSLogin DNN
    //    GetCMSTickerDataSuccess = 8020,
    //    GetCMSTickerDataFailed = 8021,
    //    GetCMSImageBannerDataSuccess = 8022,
    //    GetCMSImageBannerDataFailed = 8023,
    //    GetCMSGyankoshDataSuccess = 8024,
    //    GetCMSGyankoshDataFailed = 8025,
    //    GetCMSLatestSchemesDataSuccess = 8026,
    //    GetCMSLatestSchemesDataFailed = 8027,
    //    GetCMSSliderImageDataSuccess = 8028,
    //    GetCMSSliderImageDataFailed = 8029
    //    #endregion
    //}

    public enum MessageTypeId
    {
        LoginSuccess = 1,
        LoginUnSuccess = 2,
        Exception = 3,
        CustomerAccountExists = 4,
        CustomerAccountDoesNotExists = 5,
        BeneficiaryDetailsFound = 6,
        BeneficiaryDetailsNotFound = 7,
        BeneficiaryAdded = 8,
        BeneficiaryCouldNotBeAdded = 9,
        IFSCDetailsFound = 10,
        IFSCDetailsNotFound = 11,
        BiometricVerificationSuccess = 12,
        BiometricVerificationFailed = 13,
        AccountToAccountFundTransferSuccess = 14,
        AccountToAccountFundTransferFailed = 15,
        IMPSFundTransferSuccess = 16,
        IMPSFundTransferFailed = 17,
        NEFTFundTransferSuccess = 18,
        NEFTFundTransferFailed = 19,
        RTGSFundTransferSuccess = 20,
        RTGSFundTransferFailed = 21,
        KYCExists = 22,
        KYCDoesNotExists = 23,
        CustomerDocumentsUploadedSuccessfully = 24,
        CustomerDocumentsCouldNotbeUploadedSuccessfully = 25,
        FingerPrintDetailsisSaved = 26,
        FingerPrintDetailsisnotSaved = 27,
        CustomerAccountNumberIsCreated = 28,
        AccountOpeningCardLinkedSuccess = 361,
        CustomerAccountNumberIsNotCreated = 29,
        CashDepositSuccess = 30,
        CashDepositFailed = 31,
        CASAPLUSFundTransferSuccess = 731,
        CASAPLUSFundTransferFailed = 732,
        CASAPLUSViewBalanceSuccess = 733,
        CASAPLUSViewBalanceFailed = 734,
        CASAPLUSViewStatementSuccess = 808,
        CASAPLUSViewStatementFailed = 809,
        CashWithdrawSuccess = 32,
        CashWithdrawFailed = 33,
        OTPGeneratedSuccessfully = 50,
        OTPGenerationFailed = 51,
        OTPAlreadyUsed = 52,
        OTPVerifiedSuccessfully = 53,
        OTPVerificationFailed = 54,
        OTPHasBeenExpired = 55,
        SMSSentSuccessfully = 56,
        SMSSendingFailed = 57,
        InsertOTPSuccess = 58,
        InsertOTPFailed = 59,
        InsertSMSSuccess = 60,
        InsertSMSFailed = 61,
        ServerError = 64,
        AuthenticateSuccess = 65,
        AuthenticateUnSuccess = 66,
        SessionExpired = 67,
        NotificationSentSuccessfully = 68,
        NotificationSentFailed = 69,
        CustomerDetailsFound = 70,
        CustomerDetailsNotFound = 71,
        BeneficiaryDeleted = 72,
        BeneficiaryCouldNotDeleted = 73,
        EmailloadingSuccessful = 74,
        EmailloadingFailed = 75,
        CashCountSuccess = 76,
        CashCountError = 77,
        MiniStatementSuccessful = 78,
        MiniStatementFailed = 79,
        InterestCertificateFailed = 1011,
        InterestCertificateSuccessful = 1012,
        IFSCCodeSuccess = 80,
        IFSCCodeError = 81,
        InstaKitNumberSuccess = 82,
        InstaKitNumberFailed = 83,
        NSDLSuccess = 84,
        NSDLFailed = 85,
        FingerPrintMatchSucess = 86,
        FingerPrintMatchFailed = 87,
        AUADataFetchSucess = 88,
        AUADataFetchFailed = 89,
        UIDFoundSucess = 90,
        UIDFoundFailed = 91,
        LogoutSuccessful = 92,
        LogoutFailed = 93,
        NEFTTransactionTimingSuccess = 94,
        NEFTTransactionTimingFailed = 95,
        AuthContextDetailsSuccess = 96,
        AuthContextDetailsFailed = 97,
        UnableToGetEncryptionKey = 98,
        TellerProofSuccess = 99,
        TellerProofFailed = 100,
        BranchProofSuccess = 102,
        BranchProofFailed = 103,
        AccountHistorySuccess = 104,
        AccountHistoryFailed = 105,
        CustomerUpdateSuccessfully = 106,
        CustomerUpdateFailed = 107,
        ChargesCheckSuccessfully = 108,
        ChargesCheckFailed = 109,
        PostTransactionSuccessfully = 110,
        PostTransactionFailed = 111,
        DeleteBeneficiarySuccessful = 112,
        DeleteBeneficiaryFailed = 113,
        PanValidationSuccess = 114,
        PanValidationFailed = 115,
        SetSMSCommunicationPreferenceSuccess = 901,
        SetSMSCommunicationPreferenceFailed = 902,
        GetCustomerPhotoSuccess = 116,
        GetCustomerPhotoFailed = 117,
        FpVerificationSuccess = 118,
        FpVerificationFailed = 119,
        UpdateCustomerPhotoSuccess = 120,
        UpdateCustomerPhotoFailed = 121,
        TokenValidationSuccess = 122,
        TokenValidationFailed = 123,
        AddBillerSuccesful = 124,
        AddBillerFailed = 125,
        RechargeQuerySuccessful = 126,
        RechargeQueryFailed = 127,
        ValidateRechargeSuccessful = 128,
        ValidateRechargeFailed = 129,
        PaymentandRechargeDetailsSourceDebitSuccessful = 130,
        PaymentandRechargeDetailsSourceDebitFailed = 131,
        DeleteBillersSuccessful = 132,
        DeleteBillersFailed = 133,
        ViewBillsSuccessful = 134,
        ViewBillsFailed = 135,
        PaymentOnlyDetailsSuccesful = 136,
        PaymentOnlyDetailsFailed = 137,
        ViewBillerAccountSuccessful = 138,
        ViewBillerAccountFailed = 139,
        ViewLastPaidBillsSuccessful = 140,
        ViewLastPaidBillsFailed = 141,
        CheckTransactionStatusSuccessful = 142,
        CheckTransactionStatusFailed = 143,
        BillerValidationsSuccessful = 144,
        BillerValidationsFailed = 145,
        SetAutoPaySuccesful = 146,
        SetAutoPayFailed = 147,
        ViewScheduledBillsSuccesful = 148,
        ViewScheduledBillsFailed = 149,
        Modify_DeleteAutoPaySuccessful = 150,
        Modify_DeleteAutoPayFailed = 151,
        StopScheduledTransactionSuccessful = 152,
        StopScheduledTransactionFailed = 153,
        BillFetchDetailsSuccesful = 154,
        BillFetchDetailsFailed = 155,
        FPTemplatenotfound = 156,
        IMPSWalletAccountSuccess = 158,
        IMPSWalletAccountFailed = 159,
        PassbookUpdationSuccessful = 160,
        PassbookUpdationFailed = 161,
        AadhaarLPGSeedingSuccessful = 162,
        AadhaarLPGSeedingFailed = 163,
        NomineeAdditionSuccessful = 164,
        NomineeAdditionFailed = 165,
        NominationupadationSuccessful = 166,
        NominationupadationFailed = 167,
        DBTLSeedingSuccessful = 168,
        DBTLSeedingFailed = 169,
        RevisionDetailsSuccess = 170,
        RevisionDetailsFailed = 171,
        GetDMSdataSuccess = 172,
        GetDMSdataFailed = 173,
        //Added by Vaibhav
        #region [Krazy Bee Loan]
        KrazybeeDataInsertionSuccess = 700605,
        KrazybeeDataInsertionFailed = 700606,
        IIFlCustomerNotExists = 700607,
        IIFlCustomerExists = 700608,
        #endregion

        #region [Digital Loan]
        Loantokencreationfailed = 700615,
        DocumentMasterfound = 700616,
        DocumentMasterNotfound = 700617,
        LoanRequestSubmittedSuccessfully = 700618,
        LoanRequestFailed = 700619,
        Lenderfielddetailsfound = 700620,
        Lenderfielddetailsnotfound = 700621,
        Loanstatusavailable = 700622,
        Loanstatusnotavailable = 700623,
        Lenderdetailsfound = 700624,
        Lenderdetailsnotfound = 700625,

        Eligible = 700630,
        NotEligible = 700631,
        LoanDetailsFound = 700632,
        LoanDetailsNotFound = 700633,
        WithdrawalSuccessfull = 700634,
        WithdrawalFailed = 700635,
        AccountStatementGenerate = 700636,
        AccountStatementFailed = 700637,
        RepaymentDone = 700638,
        RepaymentFails = 700639,
        #endregion

        #region [Cleaver Tap Myprofile]
        PreferredlanguageSelected = 700609,
        PreferredlanguageNotAvailable = 700610,
        PreferredlanguageSaved = 700611,
        PreferredlanguageNotSaved = 700612,
        #endregion
        //
        SimpleWalletCreationSuccess = 174,
        SimpleWalletCreationUnSuccess = 175,
        AccountRelationshipAddSuccess = 176,
        AccountRelationshipAddFailed = 177,
        AccountRelationshipDeleteSuccess = 178,
        AccountRelationshipDeleteFailed = 179,
        SearchDMSDetailsSuccess = 180,
        SearchDMSDetailsFailed = 181,
        CustomerDataUpdateSuccess = 182,
        CustomerDataUpdateFailed = 183,
        IMPSTransactionUpdateSuccess = 184,
        IMPSTransactionUpdateFailed = 185,
        UserAlreadyExist = 186,
        CustomerDetailsSuccessful = 187,
        CustomerDetailsFailed = 188,
        AccountDetailsSuccessful = 189,
        AccountDetailsFailed = 190,
        EmailSendSuccessfully = 191,
        EmailSendFailed = 192,
        ServiceReqChargesSuccessful = 193,
        ServiceReqChargesFailed = 194,
        EsbOtpGenerationSuccessful = 197,
        EsbOtpGenerationFailed = 198,
        EsbOtpVerifySuccessful = 199,
        EsbOtpVerifyFailed = 200,
        EsbEsbSMSTemplateSuccessful = 201,
        EsbEsbSMSTemplateFailed = 202,
        OperatorandPlanDetailsFetchSuccessful = 203,
        OperatorandPlanDetailsFetchFailed = 204,
        MasterDataFound = 205,
        MasterDataCouldNotFound = 206,
        TransactionProfileDetailsSuccessful = 207,
        TransactionProfileDetailsFailed = 208,
        MasterVersionReturnSuccessFul = 209,
        MasterVersionReturnFailed = 210,
        MasterCacheResetSuccessful = 211,
        MasterCacheResetfailed = 212,
        GetGLAccountBalanceSuccess = 215,
        GetGLAccountBalanceFailed = 216,
        RemoveAccountRestrictionSuccess = 217,
        RemoveAccountRestrictionFailed = 218,
        GetTransactionAuthProfileSuccess = 219,
        GetTransactionAuthProfileFailed = 220,
        UserUnlockSuccess = 221,
        UserUnlockFailed = 222,
        //UnBlockUser
        UnblockAuthFailed = 800,
        UnblockUserSuccess = 801,
        UnblockUserFailed = 802,
        UnblockUserAlreadyActive = 803,
        UnblockUnabletoProcess = 804,
        UnblockRequestError = 805,
        UnblockUserFound = 806,
        UnblockUserR1NotFound = 807,
        UnblockUserPasswordChangedSuccess = 810,
        UnblockUserMerchantDeviceNotAllowed = 815,
        UnblockUserMerchantPANDoesnotMatch = 818,
        UnblockUserMerchantDOBDoesnotMatch = 819,
        UnblockUserMerchantDOBandPANDoesnotMatch = 820,
        UnblockUserMerchantPANNotFound = 823,
        UnblockUserMerchantContacthelpdesk = 824,
        UnblockUserMerchantExceedsLoginLimit = 825,
        //End-UnBlockUser
        setMobileBankingPINSuccess = 223,
        setMobileBankingPINFailed = 224,
        RegisterMBCustomerSuccess = 225,
        RegisterMBCustomerFailed = 226,
        changemobilebankingpinsuccess = 227,
        changemobilebankingpinfailed = 228,
        GetSecretQuestionSuccess = 229,
        GetSecretQuestionFailed = 230,
        UpdateSecretQuestionSuccess = 231,
        UpdateSecretFailed = 232,
        SetMerchantStatusSuccess = 641,
        SetMerchantStatusFailed = 642,
        GetMerchantStatusSuccess = 643,
        GetMerchantStatusFailed = 644,
        ValidUserSuccess = 235,
        ValidUserFailed = 236,
        EncryptedKeySuccess = 237,
        EmcryptedKeyFailed = 238,
        BillPaymentTransactionFailed = 252,
        BillPaymentTransactionSuccess = 253,
        BillPayTransactioninProcesskindlycheckministatement = 615,
        RechargeTransactioninProcesskindlycheckministatement = 616,
        ValidateUserSecretQuestionSuccess = 254,
        ValidateUserSecretQuestionFailed = 255,
        RechargeTransactionFailed = 266,
        RechargeTransactionSuccess = 267,
        PasswordResetSuccess = 270,
        PasswordResetFailed = 271,
        PasswordChangeSuccess = 272,
        PasswordChangeFailed = 273,
        SecretQuestionListSuccess = 274,
        SecretQuestionListFailed = 275,
        ExtraBeneficiaryDetailsFound = 213,
        ExtraBeneficiaryDetailsNotFound = 214,
        InvalidRequest = 215,
        GLAccountBalanceDetailsFound = 256,
        GLAccountBalanceDetailsNotFound = 257,
        //BillPaymentTransactionFailed = 252,
        //BillPaymentTransactionSuccess = 253,
        InterBankTransferSuccess = 264,
        InterBankTransferFailed = 265,
        //RechargeTransactionFailed = 266,
        //RechargeTransactionSuccess = 267,
        RemitanceAccountOpeningSuccess = 268,
        RemitanceAccountOpeningFailed = 269,
        InsurancePremiumPaidSuccessful = 298,
        InsurancePremiumPaidFailed = 299,
        InsuranceClaimSuccessful = 613,
        InsuranceClaimFailed = 614,
        PrintFormatDataFound = 743,
        PrintFormatDataNotFound = 744,
        ResetPrintFormatMasterDataSuccess = 745,
        ResetPrintFormatMasterDataFailed = 746,

        GetExternalAccountDetailsSuccessful = 600,
        GetExternalAccountDetailsFailed = 601,
        BeneVerificationChargesSuccess = 300,
        BeneVerificationChargesFailed = 301,
        SequenceListReturnSuccessful = 278,
        SequenceListReturnfailed = 279,
        TabControlsReturnSuccessFul = 280,
        TabControlsReturnFailed = 281,
        CreateCustomerWalletSuccess = 282,
        CreateCustomerWalletFailed = 283,
        FindCustomerSuccess = 284,
        FindCustomerFailed = 285,
        AuthProfileSuccess = 286,
        AuthProfileFailed = 287,
        AuthenticateSuccesss = 288,
        AuthenticateFailed = 289,
        PublicKeySendSuccess = 290,
        PublicKeySendFailed = 291,
        MenuListByChannelSentSuccess = 292,
        MenuListByChannelFailed = 293,
        ProfileTypeTransByChannelSuccess = 294,
        ProfileTypeTransByChannelFailed = 295,
        ProductTransByChannelSuccess = 296,
        ProductTransByChannelFailed = 297,

        ProductWiseTransactionListSuccess = 302,
        ProductWiseTransactionListFailed = 303,
        BeneUpdateSuccess = 304,
        BeneUpdateFailed = 305,
        WalkInCustomerDetailsSuccess = 306,
        WalkInCustomerDetailsFailed = 307,
        WalkInTransactionDetailsSuccess = 308,
        WalkInTransactionDetailsFailed = 309,
        AccountLimitDetailsSuccess = 310,
        AccountLimitDetailsFailed = 311,
        SupervisiorDetailsSuccess = 312,
        SupervisiorDetailsFailed = 313,
        AccountRestrictionInfoSuccess = 314,
        AccountRestrictionInfoFailed = 315,
        AccountOpeningRequestDetailsSuccess = 362,
        AccountOpeningRequestDetailsFailed = 363,
        AccountOpeningEsignSuccess = 715,
        AccountOpeningEsignFailed = 716,
        AccountDetailsSuccess = 617,
        AccountDetailsFail = 618,
        DebitkitDetailsSuccess = 629,
        DebitKitdetailsFailed = 630,
        ServiceRequestCountSuccess = 633,
        ServiceRequestCountFailed = 634,
        LMSAccountBalHoldInfoSuccess = 377,
        LMSAccountBalHoldInfoFailed = 378,
        BeneVerificationSuccess = 316,
        BeneVerificationFailed = 317,
        UserDetailSuccess = 318,
        UserDetailUnSuccess = 319,
        ResetMenuCacheSuccessful = 320,
        ResetMenuCacheFailed = 321,
        ResetProfileSuccessful = 322,
        ResetProfileFailed = 323,
        FavouriteTransactionSuccessful = 324,
        FavouriteTransactionFailed = 325,
        GetAccountStatementSuccessful = 326,
        GetAccountStatementFaliled = 327,
        ManagementHealthAPIsuccessful = 328,
        UpdateKitStatussuccessfull = 329,
        UpdateKitStatusUnsuccessfull = 330,
        WelcomeKITAcknowlegementStatusSuccess = 741,
        WelcomeKITAcknowlegementStatusFailed = 742,
        DMSGetAccountStatusSuccess = 821,
        DMSGetAccountStatusFailed = 822,
        DMSAdharVaultStatusSuccess = 836,
        DMSAdharVaultStatusFailed = 837,
        GetWorkingAddressSuccess = 842,
        GetWorkingAddressFailed = 843,
        GetForm60StatusSuccess = 844,
        GetForm60StatusFailed = 845,
        GetAadhaarLinkStatusSuccess = 846,
        GetAadhaarLinkStatusFailed = 847,
        GetAdharSeedingEnquirySuccess = 870,
        GetAdharSeedingEnquiryFailed = 871,
        GetDMSMobileDedupeSuccess = 872,
        GetDMSMobileDedupeFailed = 873,
        Branchreportsuccess = 331,
        Branchreportfailed = 332,
        Branchchannelreportsuccess = 333,
        Branchchannelreportfailed = 334,
        BranchProductreportsuccess = 335,
        BranchProductreportfailed = 336,
        BranchTranstypereportsuccess = 337,
        BranchTranstypereportfailed = 338,
        Channelreportsuccess = 339,
        Channelreportfailed = 340,
        ChannelProductreportsuccess = 341,
        ChannelProductreportfailed = 342,
        ChannelTranstypereportsuccess = 343,
        ChannelTranstypereportfailed = 344,
        Customerreportsuccess = 345,
        Customerreportfailed = 346,
        Productreportsuccess = 347,
        Productreporfailed = 348,
        Transtypereportsuccess = 349,
        Transtypereportfailed = 350,
        Userreportsuccess = 351,
        Userreportfailed = 352,
        UserProductreportsuccess = 353,
        UserProductreportfailed = 354,
        UserTranstypereportsuccess = 355,
        UserTranstypereportfailed = 356,
        TransListreportsuccess = 357,
        TransListreportfailed = 358,
        Ministatementreportsuccess = 359,
        Ministatementreportfailed = 360,
        UserWiseProductListSuccess = 361,
        UserWiseProductListFailed = 362,
        ServiceRequestStatusSuccess = 363,
        ServiceRequestStatusFailed = 364,
        CashCollectionVerificationSuccessful = 365,
        CashCollectionVerificationFailed = 366,
        CashCollectionTransactionSuccessful = 611,
        CashCollectionTransactionFailed = 612,
        CashCollectionAdhaarValidationSuccessful = 649,
        CashCollectionAdhaarValidationFailed = 650,
        SupervisorUserDetailsSuccess = 371,
        SupervisorUserDetailsFailed = 372,
        LockUserDetailsSuccess = 373,
        LockUserDetailsFailed = 374,
        UnLockUserDetailsSuccess = 375,
        UnLockUserDetailsFailed = 376,
        RemoveAccountRestrictSuccess = 377,
        RemoveAccountRestrictFailed = 378,
        KeyExchangedSuccessful = 379,
        CardTransactionSuccessful = 380,
        BalanceEnquirySuccessful = 381,
        cardtransactionBalanceEnquiryFailed = 604,
        CardTransactioncashwithdrawalFailed = 605,
        KeyExchangedFailed = 606,
        SetCardPinSuccessfull = 382,
        Invaliduserid = 912,
        InvalidTerminal = 913,
        Transactionfailed = 914,

        verifyTPINSuccess = 403,
        verifyTPINFailed = 404,
        GetclosureAmountSuccess = 405,
        GetclosureAmountFailed = 406,

        EJLogsSuccess = 700540,
        EJLogsFailure = 700541,

        Croselfaild = 747,
        Croselsucess = 748,

        AccountRistrictionSuccess = 700615,
        AccountRistrictionFailed = 700616,
        // Customer Grievance Data Get mesages
        CustomerGrievanceDataGetFailed = 603,
        CustomerGrievanceDataGetSuccessful = 602,
        TrackSuryesSuccess = 635,
        TrackSurveysFailed = 636,
        AccountCheckSuccess = 637,
        AccountCheckFailed = 638,
        DMSChequeIssuanceValidationSuccess = 811,
        DMSChequeIssuanceValidationFailed = 812,
        DMSChequeIssuanceAPISuccess = 813,
        DMSChequeIssuanceAPIFailed = 814,
        DMSKitRequestSuccess = 697,
        DMSKitRequestFailed = 698,
        DMSKitStatusUpdatedSuccess = 647,
        DMSKitStatusUpdatedFailed = 648,
        DMSKitSearchSuccess = 701,
        DMSKitSearchFailed = 702,
        UpdateSISuccess = 651,
        UpdateSIFailed = 652,
        ViewSIListSuccess = 653,
        ViewSIListFailed = 654,
        CreateSIRequestSuccess = 655,
        CreateSIRequestFailed = 656,
        DeleteSISuccess = 657,
        DeleteSIFailed = 658,
        TagDetailsSuccess = 707,
        TagDetailFailed = 708,
        TagDetailsGetSuccess = 709,
        TagDetailsGetFailed = 710,
        IFTFileApprovedSuccess = 717,
        IFTFileApprovedFailed = 718,
        GetFileDetailsSuccess = 719,
        GetFileDetailsFailed = 720,
        GetCheckerDashboardDataSuccess = 747,
        GetCheckerDashboardDataFailed = 748,
        GetApproverDashboardDataSuccess = 749,
        GetApproverDashboardDataFailed = 750,
        //DMT PPI Transaction Messages

        SearchWalkingCustomersSuccess = 367,
        WalkinCustomerLimitSuccess = 368,
        WalkinDMTImpsNeftSuccess = 430,
        SearchWalkingCustomersFailed = 370,
        WalkinCustomerLimitFailed = 371,
        WalkinDMTImpsNeftFailed = 431,

        //Lending Acc
        HHVDownloadSuccess = 434,
        HHVDownloadFailed = 435,
        CGTUploadSuccess = 436,
        CGTUploadFailed = 437,
        RCGTUploadSuccess = 438,
        RCGTUploadFailed = 439,
        SaralHHVUploadSuccess = 440,
        SaralHHVUploadfailed = 441,
        LUCSolarDownloadSuccess = 442,
        LUCSolarDownloadFailed = 443,
        LUCSolarUploadSuccess = 444,
        LUCSolarUploadfailed = 445,
        HolidayDemandDownloadSuccess = 446,
        HolidayDemandDownloadFailed = 447,
        MaturityDemandDownloadSuccess = 448,
        MaturityDemandDownloadFailed = 449,
        RegularDemandDownloadSuccess = 450,
        RegularDemandFailed = 451,
        GroupCenterAttendanceSuccess = 452,
        GroupCenterAttendanceFailed = 453,
        LoanTxnDataSuccess = 454,
        LoanTxnDataFailed = 456,
        GTRDownLoadwebServiceSuccess = 457,
        GTRDownLoadwebServiceFailed = 458,
        RECGTDownloadwebServiceSuccess = 459,
        RECGTDownloadwebServiceFailed = 460,
        HHVDownLoadwebServiceSuccess = 461,
        HHVDownLoadwebServiceFailed = 462,
        GRTUploadDataSuccess = 471,
        GRTUploadDataFailed = 472,
        CreditinquiryServiceSuccess = 473,
        CreditinquiryServiceFailed = 474,
        AdvanceNForeClosureSuccess = 475,
        AdvanceNForeClosureFailed = 476,
        ESBCustomSearchSuccess = 477,
        ESBCustomSearchFailed = 478,
        GetCenterGroupDataSuccess = 479,
        GetCenterGroupDataFailed = 480,
        DisbursementCustomersDataSuccess = 481,
        DisbursementCustomersDataFailed = 482,
        GetEnrollmentDetailSuccess = 483,
        GetEnrollmentDetailFailed = 484,
        PostcustomerDisbursementSuccess = 485,
        PostcustomerDisbursementFailed = 486,
        Esb25LegTransactionRepaySuccess = 487,
        Esb25LegTransactionRepayFailed = 488,
        EsbHOApprovalSuccess = 489,
        EsbHOApprovalFailed = 490,
        EsbProbableCenterDownloadSuccess = 491,
        EsbProbableCenterDownloadFailed = 492,
        EsbAdvanceAndForeClosureSuccess = 515,
        EsbAdvanceAndForeClosureFailed = 516,
        EsbTransactionUpdateHoverSuccess = 517,
        EsbTransactionUpdateHoverFailed = 518,
        EsbTransactionRepaymentHoverSuccess = 519,
        EsbTransactionRepaymentHoverFailed = 520,
        EsbEODCompletionSuccess = 521,
        EsbEODCompletionFailed = 522,
        CardStatusUpdateSuscess = 509,
        CardStatusUpdateFailed = 510,
        CardIssuanceSuccess = 511,
        CardIssuanceFailed = 512,

        JayamMMiniStmtSuccess = 639,
        JayamMiniStmtFailed = 640,
        RivigoDisbursementSuccess = 645,
        RivigoDisbursementFailed = 646,
        UserSurveySuccess = 659,
        UserSurveyFailed = 660,
        JayamEnrollmentAccountOpeningSuccess = 665,
        JayamEnrollmentAccountOpeningFailed = 666,

        #region Fast Tag
        FasttagVehicleregSucessful = 669,
        FasttagVehicleregFailed = 670,
        FasttagregistrationdetailsFound = 671,
        FasttagregistrationdetailsnotFound = 673,

        FastagBarcodeMappingSuccessful = 8012,
        FastagBarcodeMappingFailed = 8013,
        registeredVehicleStatusSuccessful = 8014,
        registeredVehicleStatusFailed = 8015,
        BpayPrefilledVehicleDetailssuccess = 8016,
        BpayPrefilledVehicleDetailsFailed = 8017,
        BpayRegistrationDeletionSucessful = 8018,
        BpayRegistrationDeletionfailed = 8019,



        VehicleTagIssuranceSuccessful = 675,
        VehicleTagIssuranceFailed = 676,
        VehiclePostTransactionSuccessful = 674,
        VehiclePostTransactionFailed = 672,
        VehicleVerificationCodeSuccessful = 679,
        VehicleVarificationCodeFailed = 680,

        VerificationCodeSendSucessfully = 681,
        VerificationCodeSendFailed = 682,

        TagblockSucessfully = 685,
        TagblockFailed = 686,
        TagUnblockSucessfully = 687,
        TagUnblockFailed = 688,
        DMSTagVerificationSuccessful = 689,
        DMSTagVerificationFailed = 690,

        ExceptionAmountSuccessful = 691,
        ExceptionAmountFailed = 692,

        TagCloseSucessful = 693,
        TagCloseFailed = 694,

        TagReissuanceSucessful = 699,
        TagReissuanceFailed = 700,

        GetTransactionDetailsSuccessful = 711,
        GetTransactionDetailsFailed = 712,

        UpdateCBSStatusSuccess = 713,
        UpdateCBSStatusFailed = 714,
        FasttaInvalidRequest = 1371,
        FasttaInvalidVehicleDetails = 1372,
        FasttagWalletisalreadyOpen = 1373,
        Fasttagcustcustomeraccountdetailfailed = 1374,
        Fasttagvehiclisblacklist = 1375,
        FasttagUnabletoconnectremotserver = 1376,
        FasttagMinistatment = 1377,
        FasttagVehiclealredyregister = 1378,
        FasttagVehiclealnotregister = 1379,
        FasttagUPADetailFound = 1380,
        FasttagUPADetailnotFound = 1381,
        FasttagDetailnotFound = 1382,
        FasttagServernotresponding = 1383,
        Fasttagupaaccnoupdatesuccess = 1384,
        Fasttagupaaccnoupdatefailed = 1385,
        Fasttagvirtualaddnotfound = 1386,
        FasttagSuccess = 1387,
        FasttagFailed = 1388,
        FasttagRecordnotfound = 1389,
        FasttagVehicletypeupdatesucessfully = 1390,
        FasttagVehicletypeupdatefailed = 1391,
        FasttagOTPverifyfailed = 1393,
        FasttagFPverifyfailed = 1394,
        Fasttagotpexpired = 1395,
        Fasttagverifycodesucess = 1396,
        Fasttagverifycodefailed = 1397,
        Fasttaginternalservererror = 1398,
        Fasttagverifycodesucessti = 1399,
        Fasttagverifycodefailedti = 1400,


        #endregion

        GetIINMasterDataSuccess = 735,
        GetIINMasterDataFailed = 736,

        ResetIINMasterDataSuccess = 737,
        ResetIINMasterDataFailed = 738,

        #region CashProcess message
        CashProcessUserDetailsSuccess = 407,
        CashProcessUserDetailsFailed = 408,
        CashProcessVaultDetailsSuccess = 409,
        CashProcessVaultDetailsFailed = 410,
        CashProcessVaultBalanceSuccess = 413,
        CashProcessVaultBalanceFailed = 414,
        EodProcessUserdetailsSuccess = 625,
        EodUserDetailsFailed = 626,
        EodProcessTransactionSuccess = 627,
        EodProcessTransactionFailed = 628,
        EodBranchcloseProcessSuccess = 631,
        EodBranchcloseProcessFailed = 632,
        EodUserDetailsfailed = 918,
        CBSPostingGetUserDtailsSuccess = 725,
        CBSPostingGetUserDtailsFailed = 726,
        CBSPostTransactionSuccess = 727,
        CBSPostTransactionFailed = 728,
        DMSTrackRevisionSuccess = 729,
        DMSTrackRevisionFailed = 730,

        #endregion

        #region Reversal Transaction
        ReversalTransactionSuccess = 411,
        ReversalTransactionFailed = 412,
        #endregion
        #region Bucket
        UpdateBucketBalanceSuccess = 415,
        UpdateBucketBalanceFailed = 416,
        #endregion

        #region AEPS transaction
        AEPStransactionSuccess = 417,
        AEPSTransactionFailed = 418,
        AEPSBalanceEnquirySuccess = 424,
        AEPSBalanceEnquiryFailed = 427,
        #endregion

        #region Petty Transaction
        PettyCashDepositSuccess = 419,
        PettyCashDepositFailed = 420,
        PettyCashWithdrawSuccess = 421,
        PettyCashWithdrawFailed = 422,
        PettyGlBalanceSuccess = 423,
        PettyGlBalanceFailed = 426,
        PettyLimitexpense = 917,
        #endregion


        #region Reversal Transaction
        CashOutTransactionSuccess = 428,
        CashOutTransactionFailed = 429,
        #endregion

        #region Maker Checker Message
        GetMakerSuccess = 493,
        GetMakerFailed = 494,
        GetCheckerSuccess = 495,
        GetCheckerFailed = 496,
        MakerPostSuccess = 497,
        MakerPostFailed = 498,
        MakerCancelSuccess = 499,
        MakerCancelFailed = 500,
        CheckerApprovedSuccess = 501,
        CheckerApprovedFailed = 502,
        CheckerRejectSuccess = 503,
        CheckerRejectFailed = 504,
        #endregion

        #region IMPS/NEFT
        IMPSTransactionSuccess = 607,
        IMPSTransactionFailed = 608,
        NEFTTransactionSuccess = 609,
        NEFTTranscationFailed = 610,
        #endregion

        #region RTGS
        RTGSChargesSuccess = 505,
        RTGSChargesFailed = 506,
        RTGSTransactionSuccess = 507,
        RTGSTransactionFailed = 508,
        #endregion RTGS

        #region CDM

        CDMVerificationFailed = 622,
        CDMTransactionFailed = 620,

        #endregion
        #region Shopkeeper Policy Insurance
        IPRUShubrakshaFetchDetailsFailed = 739,
        IPRUShubrakshaFetchDetailsSuccessfully = 740,
        #endregion

        #region Shopkeeper Policy Insurance

        ShopkeeperPolicyFetchDetailsSuccessfully = 661,
        ShopkeeperPolicyFetchDetailsFailed = 662,
        ShopkeeperPolicyUpdateDetailsSuccessfully = 663,
        ShopkeeperPolicyUpdateDetailsFailed = 664,

        #endregion

        #region Hospicash Policy Insurance

        HospicashPolicyFetchDetailsSuccessfully = 667,
        HospicashPolicyFetchDetailsFailed = 668,
        HospicashPolicyFetchUHIDStatusDetailsSuccessfully = 677,
        HospicashPolicyFetchUHIDStatusDetailsFailed = 678,

        #endregion

        #region Lombard Two Wheeler

        TWMasterDetailsFetchSuccessfully = 721,
        TWMasterDetailsFetchFailed = 722,
        TWQuoteGenerationSuccessfully = 723,
        TWQuoteGenerationFailed = 724,

        #endregion

        #region Last Action Lead Form

        LastActionLeadFormSuccess = 683,
        LastActionLeadFormFailed = 684,

        #endregion

        CIFKYCDetailsSuccess = 695,
        CIFKYCDetailsFailed = 696,
        SearchAgentSuccess = 703,
        SearchAgentFailed = 704,
        UpdateAgentSuccess = 705,
        UpdateAgentFailed = 706,
        //Max Id (706)
        #region RMF
        RMFFolioFailed = 700532,
        RMFFolioSuccess = 700533,
        RMFTxnSuccess = 700534,
        RMFTxnFailed = 700535,
        RMFSchemeDetailsSuccess = 700536,
        RMFSchemeDetailsFailed = 700537,
        RMFRedemptionSuccess = 700538,
        RMFRedemptionFailed = 700539,
        #endregion RMF

        GLZeroizationSuccess = 816,
        GLZeroizationFailed = 817,
        TransactionReporst_StatementSRTaken = 826,
        TransactionReporst_StatementSRUnabletoProcess = 827,
        TransactionReporst_StatementSREmailVerifyLinkSent = 828,
        TransactionReporst_StatementSREmailVerifyLinkSentFailed = 829,
        TransactionReporst_StatementSREmailUpdationFailed = 830,
        TransactionReporst_StatementSREmailNotUpdated = 831,
        TransactionReporst_StatementSREmailVerified = 832,
        TransactionReporst_StatementSREmailVPending = 833,
        TransactionReporst_StatementSREmailUpdatedSuccess = 834,
        TransactionReporst_StatementSREmailVerifyLinkExpired = 835,
        TransactionReporst_StatementSREmailAlredyVerified = 838,
        TransactionReporst_StatementSRInvalid = 839,


        #region "Cashin bank"

        Cashinbanklocationfound = 8007,
        Cashinbanklocationnotfound = 8008,

        CashinbankImagefound = 8009,
        CashinbankImagenotfound = 8010,
        CashinbankInvalidRequest = 8011,

        #endregion

        #region "Digital Passbook"
        DigitalPassbookSuccess = 700542,
        DigitalPassbookFailed = 700543,
        DigitalPassbookPDFFailed = 700544,
        #endregion


        #region "Sms Details"
        SmsDetailskSuccess = 800702,
        SmsDetailsFailed = 800703,
        #endregion

        #region "Suryoday Account Close"
        SuryodayAcnCloseSuccess = 840,
        SuryodayAcnCloseFail = 841,
        #endregion

        #region "Cash in Match data"

        CashInInsertBankStnmtSuccess = 848,
        CashInInsertBankStnmtFailuer = 849,

        CashInMatchBankStnmtSuccess = 850,
        CashInMatchBankStnmtFailuer = 851,

        CashInUpdateBankStnmtSuccess = 852,
        CashInUpdateBankStnmtFailuer = 853,

        CashInViewBankStnmtSuccess = 854,
        CashInBankStnmtFileFailuer = 855,
        CashInBankStnmtMatchBalanceFailuer = 856,

        #endregion
        #region ReferalLoan
        ReferalLoanVerificationSuccess = 857,
        ReferalLoanVerificationFailed = 858,

        #endregion

        #region merchant payouts
        GetPayoutdata = 857,
        GetPayoutdataFailure = 858,
        #endregion

        #region self declared kits
        GetSelfdeclaredkitdata = 859,
        GetSelfdeclaredkitdataFailure = 860,
        Selfdeclaredkitsave = 861,
        SelfdeclaredkitsaveFailure = 862,
        GetKitdataapproval = 863,
        GetKitdataapprovalFailure = 864,
        Approvekitdata = 865,
        ApprovekitdataFailure = 866,

        #endregion
        PincodeValidateSuccess = 867,
        PincodeValidateFailedWithRestriction = 868,
        PincodeValidateFailed = 869,

        #region bbps cust comp 1846
        checkbbpscomplaintstatusSuccess = 876,
        checkbbpscomplaintstatusFailed = 877,

        checkbbpscomplaintdataSuccess = 878,
        checkbbpscomplaintdataFailed = 879,

        SubmitbbpscomplaintdataSuccess = 874,
        SubmitbbpscomplaintdataFailed = 875,
        #endregion

        #region Foreign Remittance
        AgentCreationSuccess = 1600,
        AgentCreationFailed = 1601,

        FRTransactionSuccess = 1602,
        FRTransactionFailed = 1603,

        FRGetTransactionSuccess = 1604,
        FRGetTransactionFailed = 1605,

        FRJVVerificationSuccess = 1606,
        FRJVVerificationFailed = 1607,

        FRMasterdataSuccess = 1608,
        FRMasterdataFailed = 1609,

        FRAgentSuccess = 1610,
        FRAgentFailed = 1611,

        FRUpdateagentSuccess = 1612,
        FRUpdateagentFailed = 1613,

        FRRevisiondataSuccess = 1614,
        FRRevisiondataFailed = 1615,

        FRRevisionSuccess = 1616,
        FRRevisionFailed = 1617,

        FRDocDmsSuccess = 1618,
        FRDocDmsFailed = 1619,

        FRAckPdfSuccess = 1620,
        FRAckPdfFailed = 1621,

        FRCAReportPdfSuccess = 1622,
        FRCAReportPdfFailed = 1623,

        FRMerAgreementSuccess = 1624,
        FRMerAgreementFailed = 1625,
        #endregion


        PanUpdateInCBsSuccess = 2001,
        PanUpdateInCBSFailed = 2002,

        AccountClosureChargesSuccess = 904,
        AccountClosureChargesFailed = 905,

        DMSGuardianNumberFound = 1001,
        DMSGuardianNumberNotFound = 1002,
        LatLongUpdateSuccessfully = 1003,
        LatLongUpdateFailed = 1004,
        DMSSRCounterSuccess = 1005,
        DMSSRCounterFailed = 1006,
        ITRStatusSuccess = 906,
        ITRStatusFailed = 907,
        #region CustomerSupport
        custSupportSuccess = 908,
        custSupportFailed = 909,
        #endregion

        #region ForBillPayService
        FingerPrintAuthenFailed = 910,
        AadharAuthenFailed = 911,
        operationtimeOutMiniStatement = 915,
        operationtimeOut = 916,
        #endregion
        #region Insurance
        InsurancePremiumMismatch = 1111,
        InsuranceInvalidBadRequest = 1112,
        InsuranceBuildLatestVr = 1113,
        InsuranceOVDDetails = 1114,
        InsuranceCloseExternalAccFalied = 1115,
        InsuranceOtpAuthFailed = 1116,
        InsuranceFPverificationFalied = 1117,
        InsuranceTranTypeMismatch = 1118,
        #endregion


        #region FPBFinancial RestService
        AccountOverrideChargesSuccess = 1111,
        AccountOverrideChargesFailed = 1112,
        AnalysisFlagIs1 = 1113,
        InvalidErrorTxnLimitService = 1114,
        TxnLimitDetailsNotAvailable = 1115,
        UnableToParseTxnLimitRequest = 1116,
        InvalidErrorInGetAccountOverrideChargesAPI = 1117,
        ChargeOverrideDetailsNotAvailable = 1118,
        UnableToParseChargeOverrideRequest = 1119,
        TxnNotAllowedForSelectedProduct = 1120,
        TransactionAllowed = 1121,
        InvalidErrorInRestrictTxnByProductService = 1122,
        UnableToParseRequestData = 1123,
        #endregion

        #region BusinessLogic TransactionLimit Contract
        TxnLimitExceededTransactionFailed = 1124,
        Success = 1125,
        TxnLimitsDetailsNotFound = 1126,
        RecordNotFound = 1127,
        UnableToPerformTxnnCustomerNotExists = 1128,
        OverrideChargesCalculationFailed = 1129,
        OverrideConditionNotMatchedFetchChargesFromFIS = 1130,
        OverrideChargesNotConfigured = 1131,
        AccountChargesOverrideDetailsNotFound = 1132,
        TxnNotAllowedForWallet = 1133,
        #endregion

        #region FPBNonFinancial RestService
        UserNotAuthorizedToProceedTransaction = 1134,
        NEFTTransactionNotAllowed = 1135,
        BeneIFSCOrAccNumberCannotBeNullorEmpty = 1136,
        Mobilenumbershouldnotbenullorempty = 1137,
        TxnDetailsNotAvailableRequestData = 1138,
        WalkinTransaction = 1139,
        TxnTypeNotConfiguredForRestrictionProductCode = 1140,
        ProductCodeNotConfigured = 1370,
        #endregion

        #region BusinessLogic NonFinancial Contract
        NotalwdprfrmCshnaprvl = 1141,
        trnsctnbtwnctoftime = 1142,
        DearCstmrAplgsincnvnceplstrysvcaftr = 1143,
        Rcrdnotfndfr = 1144,
        Unbletofndcutoftime = 1145,
        PostTrnsctnnotfound = 1146,
        #endregion


        TxnUnderProccessCheckMiniStatment = 1147,
        AccountClosureFnctnltyNotApplicableWlts = 1148,
        ChannelIDNotFound = 1149,
        UserClassNotFound = 1150,
        ProductTypeNotFound = 1151,
        DearCustomerFunctionalityInoperativeBtwnCutOffTime = 1152,
        TxnDeclinedDueCreditRestrictionAccount = 1153,
        CASAPLUSViewBlnceFailed = 1154,
        TxnAmountMustLessMerchantLimit = 1155,
        InvalidAccountNumber = 1156,
        TxnNotAllowed = 1157,
        CustomerConsumeLimitFound = 1158,
        CustomerConsumeLimitNotFound = 1159,
        CashWithdrawlTxnLimitDtlsNotFoundUser = 1160,
        ServiceNotRespondingException = 1161,
        InvalidMerchantDetails = 1162,
        DearMerchantContactBranchOrSalesOfficerForSupport = 1163,
        RequestDataNotFound = 1164,
        MerchentLimitSuccess = 1165,
        MerchentLimitFail = 1166,
        GetMerchantLimitFailed = 1167,
        MerchantNotAsCustomer = 1168,
        AccountDetailsNotFound = 1169,
        NotalwdtoprfrmCshnaprvl = 1170,
        CutOffTimeFndCstmrSuccess = 1171,
        Acntnbrprdctcdnomtchdinfndcstmr = 1172,
        Cstmracntisinvld = 1173,
        //InvalidRequest = 1174,
        UnableProcceedTxnPleaseTryAagain = 1175,
        SuccessfullyInserted = 1176,
        YourRequestHasSubmittedSuccessfully = 1177,
        FailedToInsert = 1178,
        AlertNameAlreadyPresent = 1179,
        MerchantNotifictionDetailsSuccess = 1180,
        NoNewMessage = 1181,
        ServerNotRespondingPleaseTryAgainLater = 1182,
        RemoteServerReturnedError = 1183,
        AutoTxnChargesRequest = 1184,
        Banknameshuldnotbeempty = 1185,
        UnablePerformTxnDueIMPSNotAllowedSelectedBank = 1186,
        ForslctdbankIMPSNEFTtrnsctnnotallowed = 1187,
        UnblprfrmtrnsctndueTrnsctntypeshuldnotnley = 1188,
        AutoTxnSuccess = 1189,
        AutoTxnFailed = 1190,
        ErrorInSystemWhileApproving = 1191,
        GLAccountNumberNotFound = 1192,
        LimitApprovedSuccessfully = 1193,
        RequestedLimitCancelled = 1194,
        RecordExistsInCBS = 1195,
        RecordNotExistsInCBS = 1196,
        ApproveStatusUpdated = 1197,
        ErrorUpdatingApproved = 1198,
        MerchantNameNotFound = 1199,
        NoRecordFound = 1200,
        DuplicateRqustNumber = 1201,
        ModeOfTxnDataFound = 1202,
        BankDataFound = 1203,
        BankDataNotFound = 1204,
        DataFound = 1205,
        CashInIntntCountFound = 1206,
        CashInIntntCountNotFound = 1207,
        DplcteRqustNmbr = 1208,
        CustomerNumberShouldNotNull = 1209,
        FngrPrintnotactvtd = 1210,
        CustomerFPDataAvailable = 1211,
        CustomerFPDataNotExist = 1212,
        FngrPrintnotmatched = 1213,
        CustomerSupportDetailsuccess = 1214,
        CustomerSupportDtlsDataSelectionFailed = 1215,
        RequstError = 1216,
        Merchantrtinginformation = 1217,
        Merchantrtinginformationnotavailable = 1218,
        ServiceisRestricted = 1219,
        DataNotFound = 1220,
        NoDetailsFound = 1221,

        RecordNotFoundBLLDB = 1222,
        RequestNotContainXCorelationID = 1223,
        RequestDataEmpty = 1224,
        InvalidJSONTxnResponse = 1225,
        TxnResponseNotFound = 1226,
        UnableParseResponse = 1227,
        TxnDetailsNotFoundThisTxnType = 1229,
        AEPSTxnLimitDetailsNotFoundThisUser = 1230,
        InvalidUserId = 1231,
        InvalidTerminalId = 1232,
        BAVVerifiedSuccess = 1233,
        AEPSCashDepositTxnFailed = 1234,
        AEPSCashDepositSuccess = 1235,
        AEPSCashDepositFailed = 1236,
        AepsTwoFactorAuthDataInsertSuccess = 1237,
        AepsTwoFactorAuthDataInsertFailed = 1238,
        ESBServerUnavailable = 1239,
        InvalidBadRequestf = 1240,
        AEPSMiniStatementFailed = 1241,

        #region Rewards
        ServerNotRes = 1300,
        RewardDataFound = 1301,
        RewardDataNotFound = 1302,
        ClavaxDataFound = 1305,
        ClavaxDataNotFound = 1306,
        RewardStmtFound = 1307,
        RewardStmtNotFound = 1308,
        #endregion

        #region Registration
        StrCifID = 1320,
        StrCifIDNotAvailable = 1321,
        SuccessFlag = 1322,
        FailedFlag = 1323,
        InvalidUserID = 1324,
        InvalidTerminalID = 1325,
        PanValidationFailedRequest = 1326,
        PanValidationFailed_AttemptExceed = 1327,
        PanValidationFailed_PanCount = 1328,
        PanValidationFailed_signfailed = 1329,
        PanValidationFailed_AddressNotFound = 1330,
        MerlatLongSuccess = 1331,
        MerlatLongFailed = 1332,
        RequestdataNotFound = 1333,
        AcctNoNotFound = 1334,
        EKYCStatusFound = 1335,
        EKYCStatusNotFound = 1336,
        ReqFormatErr = 1337,
        MerStatusUpdate = 1338,
        MerStatusUpdateFailed = 1339,
        AddProd_pincode = 1340,
        AddProd_AllowCust = 1341,
        CustDataFound = 1342,
        CustDataNotFound = 1343,
        #endregion

        #region Lic Billpayment
        FetchLICBillpaymentDetailSuccess = 1350,
        FetchLICBillpaymentDetailFailed = 1351,
        FetchLICBillpaymentChargesSuccess = 1352,
        FetchLICBillpaymentChargesFailed = 1353,
        PostLICBillpaymentTransactionSuccess = 1354,
        PostLICBillpaymentTransactionFailed = 1355,
        #endregion
        #region Cc Billpayment
        FetchCcBillpaymentDetailSuccess = 1360,
        FetchCcBillpaymentDetailFailed = 1361,
        FetchCcBillpaymentChargesSuccess = 1362,
        FetchCcBillpaymentChargesFailed = 1363,
        PostCcBillpaymentTransactionSuccess = 1364,
        PostCcBillpaymentTransactionFailed = 1365,
        #endregion
        #region CMS Cash Collection
        TokenNotGenerated = 700600,
        DownloadLatest = 700601,
        SuspiciousTransactionDetected = 700602,
        AmtMismatch = 700603,
        BlankToken = 700604,
        MagmaCustValidation = 700613,
        #endregion

        invalidMapperID = 1401,

        #region CMSLogin DNN
        GetCMSTickerDataSuccess = 8020,
        GetCMSTickerDataFailed = 8021,
        GetCMSImageBannerDataSuccess = 8022,
        GetCMSImageBannerDataFailed = 8023,
        GetCMSGyankoshDataSuccess = 8024,
        GetCMSGyankoshDataFailed = 8025,
        GetCMSLatestSchemesDataSuccess = 8026,
        GetCMSLatestSchemesDataFailed = 8027,
        GetCMSSliderImageDataSuccess = 8028,
        GetCMSSliderImageDataFailed = 8029
        #endregion
    }
}
